### ISSUE TITLE
Which to use: TypeScript or plain JavaScript?

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#1]
Shoud we use TypeScript to develop Vivliostyle.js?

* Pros
 * Strong type checking will improve code quality
 * Some ES6 compatible features
 * Unified module syntax, which can be converted into CommonJS and AMD
* Cons
 * Requires additional build processes and dependencies
 * Additional learning cost

**Comment by johanneswilm** [comment]
Cons:
- If it will be used in other environments that we don't control, people may get annoyed by it.
- Everything may have been written in Typescript, and in two years everyone uses Coffescript noone uses Typescript. it is safer to say that Javascript will still be there.
- When making example code for specifications and alike, it has to be in plain Javascript (no dependencies), so one potentially has to think some things twice.
- For some typesetting related things, fast timing is essential (optimizing BookJS was a major task and we all know LaTeX type setting timing) and with pure Javascript one will always have an edge on interpreted languages.

Pros:
- Even if Typescript is gone in 2 years, it should be relatively simple to convert it all back to Javascript.

**Comment by johanneswilm** [comment]
I must admit I don't have such experience either. I do remember back in 2012 that Coffeescript was used a lot by certain developers who just refused to write anything else. If one wanted to include their stuff in other (non-coffee-script) projects one would first translate their code to normal javascript which would have some strange effects, such as each function having a return statement, even if none was needed. If one then tried to change some of this code and send it back upstream, one would first need to convert the patch to work with coffeescript. I don't know TypeScript enough to say whether this could also happen.

**Comment by kwkbtr** [comment]
[Flow](http://flowtype.org) can be used as a static type checker on normal JavaScript code (without extra annotations).
It will help us finding potential bugs/problems in our code, which I expected mainly from using TypeScript.
It should be easy to stop using it without affecting our code if we want to.
I will try it and see if it goes well.
