### ISSUE TITLE
起こし括弧が行頭にこない

### ISSUE THREAD

**Issue by skmtjny** [vivliostyle/vivliostyle.js#1005]
前バージョン（core: 2.17.1 / cli: 5.5.1）との比較で
改行位置が変わっている箇所があることを確認しました。

**Describe the bug**
 - 2行目以降の行頭に起こしの括弧類が来た場合、前の行の最後の文字が次行に追い出される
 - （起こしカッコ類に行頭禁則が設定されているような挙動を示す）

**Screenshots**
  ![screenshot](https://user-images.githubusercontent.com/1134887/192204249-c7f9751c-bef9-4587-9007-ae18487aa41a.png)
- 括弧類がない場合は「ほ」まで1行に収まる
- 括弧類がある場合は「ほ」が次行に追い出される
 
**To Reproduce**
 - 添付ファイルを解凍し、vivliostyle/cliでhtmlを読み込み

**Expected behavior**
 - 起こしの括弧類が行頭に表示できる状態

**Desktop**
 - OS: Windows 10 64 bit
 - Browser: Chromium 106.0.5249.30（Developer Build）（64 bit）
 - cli: 5.6.0
 - core: 2.18.1

**Additional context**
 - previewおよびbuild（PDF）で同様の状態になっていることを確認
 - 縦組み、横組み、両方でこの現象が発生することを確認
 - 前行末尾の文字により挙動が変わることを確認（添付ファイル参照）

ご確認よろしくお願いいたします。
※良いタイトルが思い浮かばなかったので不都合がありましたら
　適切なものに直していただけると幸いです・・・。

[report_220926.zip](https://github.com/vivliostyle/vivliostyle.js/files/9643367/report_220926.zip)

**Comment by MurakamiShinyu** [comment]
@skmtjny バグ報告ありがとうございます。確認しました。

起こし括弧のtext-spacingの処理とブラウザの改行の処理の関係でこの不具合が起きてました。
対策を検討します。

こちらで手を入れたテスト：
https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

inline-size: 30em の場合と inline-size: 30.5em の場合と inline-size: 30em; text-spacing: space-start の場合での挙動をテストするものです。

v2.18.1 でのテスト:
https://vivliostyle.github.io/viewer/v2.18.1/#src=https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

inline-size: 30em の場合、31文字目に起こし括弧があると30文字目の前で改行されてしまう不具合が確認できました。inline-size: 30.5em の場合には30文字目の後での改行になります。inline-size: 30em でも text-spacing: space-start（折り返し行頭の起こし括弧を詰めない）を指定するとこの不具合は起きません。また、Chromium (Chrome) 以外のブラウザ Firefox と Safari ではこの不具合は起きません。

過去のバージョン（https://vivliostyle.github.io/ にあります）をテストしましたが、v2.17.1 でも現在と同じ挙動でした。v2.15.6 から現在の挙動になっていて、その前の v2.15.5 はOKでした。

https://vivliostyle.github.io/viewer/v2.17.1/#src=https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

https://vivliostyle.github.io/viewer/v2.15.6/#src=https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

https://vivliostyle.github.io/viewer/v2.15.5/#src=https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

v2.15.6 で挙動が変わったのは次の変更の影響:
- https://github.com/vivliostyle/vivliostyle.js/pull/943

**Comment by MurakamiShinyu** [comment]
ちなみに、Vivliostyle CLI を使わないで普通のChromeでVivliostyle Viewerを使って、印刷・PDF出力すると、起こし括弧が行頭にきます。この理由は、Chromiumの内部で画面表示では新しいレイアウトエンジン、印刷では古いレイアウトエンジンという少し違うレイアウトエンジンが使われているためです（新しいレイアウトエンジンでの印刷サポートは未完成のため）。

#943 の変更の前は、両方を一致させるために、画面表示でも古いレイアウトエンジンが使われるように細工をしてました。 #943 では、CLIで印刷でも新しいレイアウトエンジンを有効にしてChromiumを起動するようにしたので、この細工を削除しました。

**Comment by MurakamiShinyu** [comment]
Fixed in https://github.com/vivliostyle/vivliostyle.js/commit/6a794827e3f84b16659bb209d9ada7fe195b4582.

Test: 
https://vivliostyle-qv2n02wh2-vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/9ca63f235c40164e0cfc70646714438f/raw/issue1005test.html

![Screen Shot 2022-09-29 at 15 42 21](https://user-images.githubusercontent.com/3324737/192958212-c2da1043-102f-4b43-9af9-ee44ad1cc9d7.png)
