### ISSUE TITLE
The Direction:RTL; is not behaving in multi column!!

### ISSUE THREAD

**Issue by namatoh** [vivliostyle/vivliostyle.js#1016]
Hi there;

I have a two column .css settings for a RTL (Right to Left [Arabic or Persian]) document. This behaves correctly when I convert my markdown to HTML in other environments and view the result in chrome! The correct way is that we should show the text in the right most column first and then over flow to the left. Again this works correctly in all media settings like "screen" or "print".

Having said that I could not find any way to make the "Vivliosyle-cli" producing the correct PDF!!

I am not so sure if this is an issue needs to be resolved or there is a work around exist for VIVLIOSTYLE to do this.

Any help?

**Comment by MurakamiShinyu** [comment]
@namatoh Thank you for reporting the bug. I confirmed the problem.

**Comment by MurakamiShinyu** [comment]
@namatoh 
I transferred this issue to Vivliostyle.js issues because the bug is in the Vivliostyle.js/core.

**Comment by namatoh** [comment]
Hello Sir,

Thanks for your swift response. I will follow it there. Please don't hesitate to let me know if I can be any help in the process.

Best wishes

**Comment by MurakamiShinyu** [comment]
I made a simple test.

Test sample: https://gist.githack.com/MurakamiShinyu/adf40126881075cda96772d2ed4e61d2/raw/rtl-columns.html

Test with Vivliostyle Viewer (v2.18.3):
https://vivliostyle.github.io/viewer/v2.18.3/#src=https://gist.githack.com/MurakamiShinyu/adf40126881075cda96772d2ed4e61d2/raw/rtl-columns.html

![Screen Shot 2022-10-05 at 12 26 07](https://user-images.githubusercontent.com/3324737/193975155-35201aac-b876-4b6a-a56d-c70fa7916bb9.png)

In this result, the column direction is wrong. The first column (starting with the heading "Arabic Lipsum") should be the right side column.

**Comment by namatoh** [comment]
yes you are absolutely right if you need I can provide a real life markdown document and a right css which works in print media of any browser but not in the vivliostyle.

**Comment by MurakamiShinyu** [comment]
@namatoh Yes, real example document and css will help. Thank you.

**Comment by namatoh** [comment]
Here they are 
[Hafez.pdf](https://github.com/vivliostyle/vivliostyle.js/files/9712970/Hafez.pdf)
[Hafez_with_footnote.md](https://github.com/vivliostyle/vivliostyle.js/files/9712971/Hafez_with_footnote.md)

and the simplified css is:

* {
    direction:rtl;
}

body {
    columns: 2;
}

and this is how it should be, done by simple print media using chrome print:

<img width="428" alt="Screenshot 2022-10-05 at 08 41 45" src="https://user-images.githubusercontent.com/49653456/193987652-e301df12-bf5c-4571-bde0-72427dc7d806.png">

**Comment by MurakamiShinyu** [comment]
Fixed in #1017.

Test sample HTML, made from [Hafez_with_footnote.md](https://github.com/vivliostyle/vivliostyle.js/files/9712971/Hafez_with_footnote.md) (thanks @namatoh): 
https://gist.githack.com/MurakamiShinyu/15169d46082376a6cf24eff79ec5f6e4/raw/Hafez_with_footnote.html

Test with Vivliostyle Viewer:
- Before this fix (v2.18.3): https://vivliostyle.github.io/viewer/v2.18.3/#src=https://gist.githack.com/MurakamiShinyu/15169d46082376a6cf24eff79ec5f6e4/raw/Hafez_with_footnote.html
- After this fix: https://vivliostyle-git-fix-issue1016-vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/15169d46082376a6cf24eff79ec5f6e4/raw/Hafez_with_footnote.html

**Comment by namatoh** [comment]
Beautiful Thanks a lot.

**Comment by MurakamiShinyu** [comment]
FYI,

The CSS spec on `direction` property https://www.w3.org/TR/css-writing-modes-3/#direction says *"we recommend HTML authors to use the HTML `dir` attribute …. Authors should not use `direction` in HTML documents."*

To generate HTML documents with `dir="rtl"` attribute, the [frontmatter](https://vivliostyle.github.io/vfm/#/vfm#frontmatter) in [VFM](https://github.com/vivliostyle/vfm) (Markdown used in Vivlioistyle CLI) will be useful. For example,

```md
---
lang: fa
dir: rtl
---

# در باره‌ی حافظ
## تولد و زندگی

```

The HTML output will be:
```html
<!doctype html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title>در باره‌ی حافظ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <section id="در-بارهی-حافظ" class="level1">
      <h1>در باره‌ی حافظ</h1>
      <section id="تولد-و-زندگی" class="level2">
        <h2>تولد و زندگی</h2>
      </section>
    </section>
  </body>
</html>
```

**Comment by namatoh** [comment]
Thanks you are right. "noted"

I normally use CSS for such thing but your suggestion is better.

When do you think I can use "VIVLIOSTYLE CLI" to generate proper PDF from the markdown which is my primary need?

By the way when this issue is resolved I would be happy to provide you with a commercially complete RTL document to be presented in the vivliostyle website as RTL referneces and educational purposes.

Thanks again for your hard work.

**Comment by MurakamiShinyu** [comment]
@namatoh 
> When do you think I can use "VIVLIOSTYLE CLI" to generate proper PDF from the markdown which is my primary need?

I am now working on other bugs and hopefully I can fix them and I will release Vivliostyle.js v2.18.4 and Vivliostyle CLI v5.6.3 within a couple of days. (Vivliostyle.js v2.18.4 Milestone: https://github.com/vivliostyle/vivliostyle.js/milestone/5 )

**Comment by namatoh** [comment]
I do understand and appreciate your hard work and behalf of the literature and publishing community send you my warmest thanks.

**Comment by MurakamiShinyu** [comment]
@namatoh Please check [Vivliostyle CLI v5.7.0](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v5.7.0) that includes Vivliostyle.js v2.18.4 in which this bug is fixed.

**Comment by namatoh** [comment]
Hi there,

Just to thank you for your support and inform you that the issue is completely been resolved and tested thoroughly. As you may be aware that currently I am in Iran and we have some internet issues as result of the social uprising. As soon as the internet issues are eased I will send you excerpt of a professionally made persian poetry book to reflect most of the RTL styling. 

Best wishes. Dr Rad
