### ISSUE TITLE
横1段組で改段すると、改段直後の段がPDFに表示されない

### ISSUE THREAD

**Issue by skmtjny** [vivliostyle/vivliostyle.js#1067]
**Describe the bug**
- 横1段組中で `break-before: column;` を使用した場合、以降の文章がPDFに表示されなくなる（Vivliostyleのプレビュー上では表示されている）
- 改頁した場合や文章が1ページを超えた場合は、その箇所から再度表示されるようになる

**Screenshots**
- 左：プレビュー　右：PDF
 
![ss](https://user-images.githubusercontent.com/1134887/208382584-ff8a83a8-5611-4800-9ba0-1510429f706f.png)

**To Reproduce**
 - 添付ファイルを解凍し、vivliostyle/cliでhtmlを読み込み
 - サンプルデータ（以下のうち、横1段の場合のみ発生することを確認）
   - 横1段（index_h1.html）
   - 横2段（index_h2.html）
   - 縦1段（index_v1.html）
   - 縦2段（index_v2.html）
   - 横1段（index_h1_break-after.html） ※break-before から break-afterに変更したもの

**Expected behavior**
 - 文章が消えずにPDFにも表示された状態

**Desktop**
 - OS: Windows 10 64 bit
 - Browser: バージョン: 108.0.5359.29（Developer Build） （64 ビット）
 - cli: 6.0.0
 - core: 2.20.0

どうぞよろしくお願いいたします。

[sample_221219.zip](https://github.com/vivliostyle/vivliostyle.js/files/10257563/sample_221219.zip)

**Comment by MurakamiShinyu** [comment]
@skmtjny 報告ありがとうございます。不具合確認しました。次のバージョンで修正します。

**Comment by MurakamiShinyu** [comment]
メモ
- Vivliostyle.js v2.15.0 (2022-05-05) 以降でこの不具合あり。
  - #912 での変更が関係している
- SafariとFirefoxでの印刷では問題なし。Chromiumだけで起きる問題。
- Vivliostyle.js は自前で段組の処理をするので、処理結果のDOMには column-count プロパティは出力しない。それなのに不必要な `break-before: column` が出力されていることで問題が起きている。

**Comment by MurakamiShinyu** [comment]
Fixed in #1069 

<img width="1477" alt="Screenshot 2022-12-21 at 15 55 12" src="https://user-images.githubusercontent.com/3324737/208841729-fc1f8ac0-f5cc-46ac-9086-d35a64692fa4.png">
