### ISSUE TITLE
Minimum font size problem

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1078]
Minimum font size problem on ruby was resolved with a workaround using the `zoom` property,

- https://github.com/vivliostyle/vivliostyle.js/issues/673

However, the problem still exists on any very small font size text other than ruby text.

----

Workaround on Google Chrome
（Google Chromeでのこの問題の回避方法）

> ## Chromeの最小フォントサイズの設定
>
> Chromeの最小フォントサイズの設定は、Chromeの「[設定](chrome://settings/)」の「デザイン」の「[フォントをカスタマイズ](chrome://settings/fonts)」にあります。デフォルトでは次のようになっています:
>
> ![chrome-min-fontsize-10px](https://user-images.githubusercontent.com/3324737/100530819-490cce00-323a-11eb-9ab7-07474838ac19.png)
>
> ↓ これを次のように 0 にすることで最小フォントサイズの問題をなくすことができます:
>
> ![chrome-min-fontsize-0](https://user-images.githubusercontent.com/3324737/100530907-23cc8f80-323b-11eb-85cc-003950a7e57b.png)

**Comment by ttrace** [comment]
%vivliostyle build [file]
 can produce a small font pdf, but following cant' show.
%vivliostyle preview [file]

**Comment by MurakamiShinyu** [comment]
@ttrace See:

- https://github.com/vivliostyle/vivliostyle.js/issues/1091

**Comment by ttrace** [comment]
thank you, I'll wait implementation of -lang=en with launching chromium.

**Comment by MurakamiShinyu** [comment]
https://github.com/vivliostyle/vivliostyle.js/issues/1091#issuecomment-1439463626

> Fixed in
> - https://github.com/vivliostyle/vivliostyle-cli/pull/376
> 
> [Vivliostyle CLI v6.3.0](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v6.3.0) includes this fix.

（この後、OSにより別の対策が必要なことが分かり再修正↓）

> - https://github.com/vivliostyle/vivliostyle-cli/pull/416


このVivliostyle CLIでの修正により、Vivliostyle CLIを使う限りは最小文字サイズの問題は解消しました。

しかし、Vivliostyle CLIを使わないでVivliostyle Viewerを通常のChromeブラウザで利用する場合にはまだこの問題があり、それを回避するには「Chromeの最小フォントサイズの設定」(👉 https://github.com/vivliostyle/vivliostyle.js/issues/673#issue-752829891) を行う必要があります。

このためこのissueはオープンのままとします。

**Comment by MurakamiShinyu** [comment]
> このVivliostyle CLIでの修正により、Vivliostyle CLIを使う限りは最小文字サイズの問題は解消しました。

と [Vivliostyle CLI v6.3.0](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v6.3.0) のリリース時点では（CLIを使う限りは）解決していたのですが、先月ごろからMacでのChromiumの仕様が変わったのか、Mac上でVivliostyle CLIで問題が復活してます。詳しくはVivliostyle CLIのIssue:

- https://github.com/vivliostyle/vivliostyle-cli/issues/399

**Comment by MurakamiShinyu** [comment]
Fixed:

- https://github.com/vivliostyle/vivliostyle-cli/pull/416

**Comment by MurakamiShinyu** [comment]
朗報！ Chromiumでこの問題が修正されて、10月リリース予定のChrome 118で最終的に解決する見込みです。

Good News! The minimum font size problem on Chrome (Chromium) has been fixed in the latest Canary version (from 118.0.5939.0). It will be released as Chrome 118 on October 10.

- Chromium bugs: [Issue 1469490: The default setting of "Minimum font size" varies by languages](https://bugs.chromium.org/p/chromium/issues/detail?id=1469490)
  > [Comment 6](https://bugs.chromium.org/p/chromium/issues/detail?id=1469490#c6) by [kojii@chromium.org](https://bugs.chromium.org/u/1636536379) on Thu, Aug 10, 2023, 8:24 PM GMT+9 Project Member  
  > **Status:** Fixed (was: Assigned)  
  > Landed 118.0.5939.0, confirmed by a quick manual test in Canary. 

---

Test sample (HTML): https://gist.githack.com/MurakamiShinyu/63fa427fa6921a6f8a957496fb9d62bb/raw/small-font-size.html

最新のGoogle Chrome Canary (118.0.5940.0)の日本語環境でのデフォルトの状態で確認したスクリーンショット：

<img width="1123" alt="スクリーンショット 2023-08-11 11 31 09" src="https://github.com/vivliostyle/vivliostyle.js/assets/3324737/41e04ce9-d82f-4034-9133-1b5611fe2a5e">

このGoogle Chrome Canaryのバージョンは：
<img width="1243" alt="スクリーンショット 2023-08-11 10 51 52" src="https://github.com/vivliostyle/vivliostyle.js/assets/3324737/b643c3e3-7803-4296-bd1d-5d7f8a37276d">

フォントの設定を見るとデフォルトで最小フォントサイズが「極小」(0)になっている：
<img width="1243" alt="スクリーンショット 2023-08-11 10 53 09" src="https://github.com/vivliostyle/vivliostyle.js/assets/3324737/63c6e281-8bb6-4d8d-bba2-58c202cf65e9">

**Comment by MurakamiShinyu** [comment]
> 朗報！ Chromiumでこの問題が修正されて、10月リリース予定のChrome 118で最終的に解決する見込みです。
> 
> Good News! The minimum font size problem on Chrome (Chromium) has been fixed in the latest Canary version (from 118.0.5939.0). It will be released as Chrome 118 on October 10.

この予告のとおり、最近リリースされたChrome 118で問題は解消しているので、このissueはクローズします。
