### ISSUE TITLE
10px未満の文字サイズ表示がビューワーとPDFで異なる

### ISSUE THREAD

**Issue by skmtjny** [vivliostyle/vivliostyle.js#1091]
**Describe the bug**
- 文字サイズを10px未満に指定した場合、ビューワーとPDFで表示結果が異なっている
  - ビューワー → 10px未満にならない（Chromiumの文字サイズ制限が適用される）
  - PDF 　　　→ 10px未満でも表示される

**Screenshots**
- 左：プレビュー　右：PDF
 
![ss](https://user-images.githubusercontent.com/1134887/211184542-6eed36de-a17d-41dd-b003-9d9bad138859.png)

**To Reproduce**
 - 添付ファイルを解凍し、vivliostyle/cliでhtmlを読み込み

**Desktop**
 - OS: Windows 10 64 bit
 - Browser: Chromium 109.0.5414.46（Developer Build） （64 ビット）
 - cli: 6.1.0
 - core: 2.21.1
 
[font-size-test_230108.zip](https://github.com/vivliostyle/vivliostyle.js/files/10367867/font-size-test_230108.zip)

**Comment by MurakamiShinyu** [comment]
Vivliostyle CLIのpreviewとbuildで結果が違うことがある理由が分かりました。

まず、このテストサンプルを私の環境でVivliostyle CLI (v6.1.0)のpreviewで表示したときのスクリーンショットは以下です：

<img width="1236" alt="Screenshot 2023-01-08 at 18 24 42" src="https://user-images.githubusercontent.com/3324737/211189099-e302ccb3-c867-4265-a2fd-91da4b236740.png">

10px未満の文字サイズが問題なく表示されてます。buildでのPDF出力と同じ結果です。

そのあと、MacOSの言語の設定が英語になっていたのを日本語に直して再起動してから同じテストをしたところ、報告されたのと同様、previewだけ10px未満の文字サイズにならなくなりました。

これは Chromium (Chrome) の最小フォントサイズのデフォルトの設定が、OSの言語設定によって変わるためです。日本語では10pxで、英語では0ということです。

日本語環境でも、ブラウザの設定メニューから最小フォントサイズの設定を0に変えることができます：

<img width="977" alt="スクリーンショット 2023-01-08 18 15 06" src="https://user-images.githubusercontent.com/3324737/211189358-479c13a0-4090-4065-8332-20602dd41b37.png">

しかし、Vivliostyle CLIのpreviewで使われるPlaywright経由で起動するChromiumでは、起動するたびにこの設定はリセットされてしまうようで、めんどうです。

Vivliostyle CLIのbuildコマンドではChromiumのHeadlessモードが使われます。このモードではOSの言語の設定によらないデフォルト（英語環境と同じ）が使われます。

CLIの前のバージョン(v6.0)までは、少し違うHeadlessモードである `--headless=chrome` というモードが使われてました。このモードでは、previewと同じくOSの言語の設定によって変わり、日本語環境ではbuildのPDF出力でも最小フォントサイズが10pxになりました。v6.1で変更した理由は以下：

- https://github.com/vivliostyle/vivliostyle-cli/issues/357

**Comment by hkwi** [comment]
ChromeのfontSettingはextensionから[設定](https://developer.chrome.com/docs/extensions/reference/fontSettings/#method-setMinimumFontSize)できるようになったようです。次のようなセットアップで、実際にvivliostyle-cliに手元で組み込んでみて、設定値が反映されるところまでは確認できました。
- extension で background.service_worker で起動時に最小値を変更する
- playwright からの起動オプションでextensionを読み込む
  - `--load-extension` と `--disable-extesions-except` （`--disable-extensions` の打消）の両方を指定
  - ただし headless mode だと persistent context 付きでないと使えない https://playwright.dev/docs/chrome-extensions

次のポイントを考慮する必要があり、patch を書くのをためらっています。
- extension の置き場所（ビルド手順も含めて）
- playwright で `launch` を `launchPersistentContext` に置き換えると、`Browser` でなく `BrowserContext` が得られる

**Comment by MurakamiShinyu** [comment]
headless modeでのPDF出力では最小フォントサイズの問題がないので、previewでだけ最小フォントサイズを0に直すことができればよいと思います。

localeがenなどであれば最小フォントサイズはデフォルトで0になるので、もしかしたら、--locale=en を設定して起動するのでも解決するかもしれません。

https://developer.chrome.com/docs/extensions/reference/i18n/#how-to-set-browsers-locale

**Comment by hkwi** [comment]
そうですね。改めて考えてみるとviewerを使う場合はユーザの手元で起動させたブラウザを使う手順になるわけですし、extensionは一貫性にも欠けてしまいそうです。preview だけの問題とするなら、`--lang=en` あたりが妥当そうですね。

ところでいろいろ経緯を眺めてみたのですが、技術的な問題というよりは、ブラウザ画面上で読めない文字を表示すべきでないというポリシーが裏にあるように読めました。css-fonts-4 でも min-font-size が削除されていました。
- https://bugs.chromium.org/p/chromium/issues/detail?id=16868
- https://bugs.chromium.org/p/chromium/issues/detail?id=36429
- https://bugs.chromium.org/p/chromium/issues/detail?id=308862

**Comment by MurakamiShinyu** [comment]
Fixed in
- https://github.com/vivliostyle/vivliostyle-cli/pull/376

[Vivliostyle CLI v6.3.0](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v6.3.0) includes this fix.
