### ISSUE TITLE
Same fonts, but different output by OS

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle.js#1098]
## Usage Environment

- MacBook Air M2 2022
    - OS: [ mac OS 13.1]]
    - Product [Vivliostyle CLI v6.1.0]
    - Browser [Chromium 109.0.5414.46（Developer Build）]
    - Font [Noto Serif CJK JP (body), Noto Sans CJK JP (heading)]
- Fujitsu LifeBook U937/P
    - OS: [ Windoes 10 Pro]]
    - Product [Vivliostyle Pub α v0.1.0]
    - Browser [Chrome 109.0.5414.75]
    - Font [Noto Serif CJK JP (body), Noto Sans CJK JP (heading)]

### Mac

<img width="889" alt="Dスクリーンショット 2023-01-17 23 42 05" src="https://user-images.githubusercontent.com/31482860/213403938-ba3e0717-ef46-4f97-af9a-0d16b76d45a0.png">

### Windows

![Dスクリーンショット (5)](https://user-images.githubusercontent.com/31482860/213403989-ee948956-5a0d-4795-b753-72a322ced49c.png)

### PDF (Mac)

![スクリーンショット 2023-01-19 18 56 56](https://user-images.githubusercontent.com/31482860/213437413-0acbed3f-ca89-43a5-a852-273606bd2682.png)

### PDF (Windows)

![スクリーンショット (22)](https://user-images.githubusercontent.com/31482860/213437474-1e7967e9-c6be-4169-a764-3284e1be6b1c.png)

### Mac

<img width="817" alt="Fスクリーンショット 2023-01-18 14 47 32" src="https://user-images.githubusercontent.com/31482860/213404045-020e0f62-1864-40c6-8359-f9325263a70a.png">

### Windows

![Fスクリーンショット (6)](https://user-images.githubusercontent.com/31482860/213404065-3fee1801-7e8d-414f-9139-29785fc3cb91.png)

### PDF (Mac)

![スクリーンショット 2023-01-19 18 57 45](https://user-images.githubusercontent.com/31482860/213437523-383bc3ad-d737-4be6-b367-10b92b464511.png)

### PDF (Windows)

![スクリーンショット (23)](https://user-images.githubusercontent.com/31482860/213437879-c7895371-eb3d-46cd-bd7f-9d481a4e85e1.png)

**Comment by ogwata** [comment]
先のレポートは、Windous (Pub) とMac (CLI)のプレビューを一致させる作業を進めながらスクリーンショットをとったので、データそのものは同一ではありません。

その作業が終わったので、今度は同じデータで条件を変えて比較してみました（ファイル名の`612ab29`はコミット番号）。

### MacBook Air- う゛ぃ

**Comment by ogwata** [comment]
> データを同一にし、環境を変えて比較したところ、不思議な行の異同が見られたので報告します（ファイル名の612ab29はコミット番号）。

上記コメントの問題はVivliostyle.jsとは無関係でした。

**Comment by MurakamiShinyu** [comment]
この問題について調べました。結論を先に書くと、各OSで使われているフォントが違うものであることが出力結果が違う原因でした。

WindowsでのVivliostyle Pubのプレビューのスクリーンショットを見ると、字形が明らかに他のOSのものと違います。
指定は、見出しフォントが `font-family: "Noto Sans CJK JP", "YuGothic", "Yu Gothic", sans-serif` で本文フォントが `font-family: "Noto Serif CJK JP", "YuMincho", "Yu Mincho", serif` のはずです。Windows環境に "Noto Sans CJK JP" と "Noto Serif CJK JP" がインストールされていなくて、フォールバックで "Yu Gothic" と "Yu Mincho" が使われているようです。したがって、このWindowsでの出力の違いはフォントが違うので当然です。

## Vivliostyle CLIのDocker (Linux)上でのNoto CJK Fontsのバージョンの問題

「PDF (Windows)」と書かれているのはVivliostyle Pubのクラウドで出力されたPDFのようです。したがってOSはWindowsではなくてDocker上で動くLinuxです。
Vivliostyle CLIを `--render-mode docker` で使用しても同じ結果が得られます。
このDockerモードで出力されるPDFが、Macの出力と違う原因を調べました。

特に違いが出ているのが、本文フォント（font-family: "Noto Serif CJK JP"）での数字の字幅です。

次のスクリーンショットは、上がDockerで、下がMacでの出力です。

<img width="1544" alt="スクリーンショット 2023-06-01 21 40 58" src="https://github.com/vivliostyle/vivliostyle.js/assets/3324737/0ea16f72-412c-45bd-8680-9d3f5d89dd7d">

次のことが分かります：

- 「1」の字幅がDockerは広めでMacは狭め
- 「1」以外の数字は逆でDockerのほうがほんの少し狭い

どうもDockerのほうでは数字の字幅が等幅で、Macのほうは数字の字幅がプロポーショナルなようです。

また、英字の字幅も微妙な違いがあります。次のスクリーンショットも上がDockerです。

<img width="887" alt="スクリーンショット 2023-06-01 23 22 44" src="https://github.com/vivliostyle/vivliostyle.js/assets/3324737/e731109b-411f-4803-a022-c8a5505d2ef0">

ほんの少しですが、字幅の違いが表れて上と下で単語「Universteskaya」の最後の「a」の位置がずれています。
（なお、この例では `font-kerning: none` を指定しているので、ペアカーニングは無関係です）

どうもフォントのバージョンが違うのではないかと考えて確かめました。

Vivliostyle CLIのDockerイメージをつくる Dockerfile
https://github.com/vivliostyle/vivliostyle-cli/blob/main/Dockerfile
でコマンド `apt-get install -y fonts-noto` により Noto CJK Fonts を含むすべての Noto Fontsがインストールされてます。

これでインストールされる Noto CJK Fonts パッケージは次のものです。

https://packages.ubuntu.com/focal/fonts-noto-cjk
> パッケージ: fonts-noto-cjk (1:20190410+repack1-2)

このパッケージの記述にある「20190410」はこのフォントが作られた日付のようです。

Noto CJK FontsのGitHubリポジトリのリリース一覧 https://github.com/notofonts/noto-cjk/releases を見ると最新のリリースは 20220127 (Noto Sans CJK Version 2.004)です。
「20190410」は[Noto Sans CJK V2.001](https://github.com/notofonts/noto-cjk/releases/tag/NotoSansV2.001)です。
このNoto Sans CJK v2.001 の時点では Noto Serif CJK のバージョンは v1.001 でした（最新は 2.001）。

このように、Vivliostyle CLIのDocker上の Noto Serif CJK バージョンが古いものであるので、最新版を入れたMacやWindowsとは出力結果が違うということです。

確認のため、「20190410」のバージョン
https://github.com/notofonts/noto-cjk/tree/NotoSansV2.001
の NotoSerifCJK-Regular.ttc などをMacにインストールして、Vivliostyle CLIからPDF出力したところ、Dockerモードの場合とまったく同じ結果になりました。

### 解決するには：Dockerで最新バージョンのNoto CJK Fontsが使えるようにすること

このフォントのバージョンの問題を解決するには、Dockerで最新バージョンのNoto CJK Fontsが使えるようにすることが必要です。（MacやWindowsに古いフォントをインストールさせる手もありますが、新しい方に合わせたほうがよいでしょうから）

現在Vivliostyle CLIのDockerはUbuntuバージョン focal (20.04LTS) ですが、これを jammy (22.04LTS) にあげると、jammy用のfonts-noto-cjkパッケージが使える。これは最新 20220127 になっている：

https://packages.ubuntu.com/jammy/fonts-noto-cjk
> パッケージ: fonts-noto-cjk (1:20220127+repack1-1)

つまり、Vivliostyle CLIのDockerはUbuntuバージョンを最新LTSのjammy (22.04LTS)にあげることで解決しそう。

**Comment by MurakamiShinyu** [comment]
Vivliostyle.jsのバグではないのでこのissueは閉じます。
