### ISSUE TITLE
Using a CSS target-counter breaks named-pages styling

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1136]
**Describe the bug**
Styling pages using @page rules with names works as long as I don't use a target-counter rule for my toc. Once I start using the target-counter, the named pages lose their styling. (Interestingly, the correct background color is shortly flashing while layouting)

**To Reproduce**
Paginate the attached very simple test document with Vivliostyle v2.22.4

**Expected behavior**
The background color of the first page should be green.

**Desktop:**
 - macOS 13.2
 - Safari 16.3

The bug also occurs when using Chrome.

[target-counter-bug.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/10868918/target-counter-bug.html.zip)

**Comment by MurakamiShinyu** [comment]
@depth42 Thank you for reporting the bug. I confirmed the problem.

**Comment by MurakamiShinyu** [comment]
Fixed in #1140.

Test: 
https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/e9087869674150f85b8d7c678cf8679c/raw/issue1136test.html
