### ISSUE TITLE
CSS target-counter and leader do not work if defined in @page

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1143]
**Describe the bug**
If I define a CSS rule with a content attribute using the leader and target-counter features, this rule is not applied if it is contained in a @page block. If I define it outside of a @page block it works fine.

**To Reproduce**
Paginate the attached very simple test document with Vivliostyle v2.23.0

**Expected behavior**
The paginated document should show leader dots and a page number.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 13.2
 - Safari 16.3

The problem also occurs in the Chrome browser.

[target-counter-leader-bug.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/11016009/target-counter-leader-bug.html.zip)

**Comment by MurakamiShinyu** [comment]
Your stylesheet:
```css
@page {
  size: A4;
  #toc a::after {
    content: leader('.') target-counter(attr(href), page);
  }
}
```

The style rule (`#toc a::after {…}`) is not allowed inside a `@page` rule. So this invalid rule is ignored.

See the [\@page rule grammar](https://drafts.csswg.org/css-page-3/#syntax-page-selector).
