### ISSUE TITLE
Integrating Vivliostyle with Puppeteer to generate PDFs in a NestJS API

### ISSUE THREAD

**Issue by MathisPct** [vivliostyle/vivliostyle.js#1155]
Hello 🙂,

I am working on a NestJS API project that receives an HTML template and generates a PDF file from a page opened via Chrome Headless using Puppeteer. I previously used Paged.js, which provides a JavaScript polyfill that I integrate into the HTML template in the Chrome page. Now, I would like to create a second route that supports the Paged Media specification but uses Vivliostyle instead.

I have installed the "@vivliostyle/core" dependency via npm, but I am having trouble integrating Vivliostyle with Puppeteer in my project.

Thank you in advance for your assistance :)

**Comment by MurakamiShinyu** [comment]
I recommend you to use Vivliostyle CLI.
https://github.com/vivliostyle/vivliostyle-cli

Vivliostyle CLI uses Playwright ([switched from Puppeteer](https://github.com/vivliostyle/vivliostyle-cli/pull/291) last year).
