### ISSUE TITLE
Page counter-reset does only work in @page rules, not in element CSS rules

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1173]
Paginate the attached document with Vivliostyle. In this constructed example, I expect the h2 rule to reset the page counter back to 1 every time a h2 is encountered, but this does not happen. If I put the counter-reset into a @page rule, it works. Am I doing something wrong?

[Archiv.zip](https://github.com/vivliostyle/vivliostyle.js/files/11422511/Archiv.zip)

**Comment by MurakamiShinyu** [comment]
This is correct behavior. The `page` counter is defined in the page context as if the rule `@page :first { counter-reset: page 0; } @page { counter-increment: page 1; }` exists, so the `page` counter has scope in the page context. If same name (`page`) counter is reset in the document (`h2` element), new counter with different scope is created, so the counter-reset in the document cannot affect the `page` counter for the page context.

See the spec: https://drafts.csswg.org/css-page-3/#page-based-counters
