### ISSUE TITLE
Error: Internal error

### ISSUE THREAD

**Issue by Zaslon** [vivliostyle/vivliostyle.js#1178]
**Describe the bug**
"Error: Internal error" occures when the book is loaded.

**To Reproduce**
1. Load this link with Chrome or Firefox on PC (https://vivliostyle.org/viewer/#src=https://github.com/Zaslon/vivliostyleIdyerDict/blob/master/%E7%B7%AF%E6%97%A5%E8%BE%9E%E5%85%B8%20%E6%9C%AC%E6%96%87.html)

**Expected behavior**
Render without errors.

**Screenshots**

Firefox：
![image](https://github.com/vivliostyle/vivliostyle.js/assets/3113625/4d8015ab-2135-43bc-ba80-b86c9fc773e3)

Chrome：
![image](https://github.com/vivliostyle/vivliostyle.js/assets/3113625/6a51b5b6-7743-4ee9-b290-1fa647794145)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser Chrome: 112.0.5615.140 (Official Build) (64 bit)
 - Browser Firefox: 113.0 (64 bit)

**Smartphone (please complete the following information):**
In this device, the bug is not reproduced.
 - Device: Pixel 6a
 - OS: Android 13
 - Browser Chrome 
 - Version: 113.0.5672.77

In this device, the bug is not reproduced.
 - Device: iPad mini (6th gen.)
 - OS: iPad OS (16.3.1)
 - Browser: Safari
 - Version: 16.3

**Comment by MurakamiShinyu** [comment]
Fixed in #1180.

Test: https://vivliostyle-git-fix-issue1178-vivliostyle.vercel.app/#src=https://github.com/Zaslon/vivliostyleIdyerDict/blob/master/%E7%B7%AF%E6%97%A5%E8%BE%9E%E5%85%B8%20%E6%9C%AC%E6%96%87.html
