### ISSUE TITLE
Element with `writing-mode: vertical-rl` looks height is wrong with Chrome

### ISSUE THREAD

**Issue by pastak** [vivliostyle/vivliostyle.js#1190]
**Describe the bug**

Reproduce case html: https://gist.github.com/pastak/f21d60c94d787b3a931a4967f332d997
Test with Vivliostyle Viewer: https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/pastak/f21d60c94d787b3a931a4967f332d997/raw/58be6f9c8fb4308998d7473b11e2efa35cf1f461/vivliostyle-testcase.xhtml

It is expected to be (with Safari)

<img width="1520" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/96bad5e5-41ca-484e-a03f-dd1904598365">

but It is with Chrome

<img width="1624" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/b3de5d6e-bb70-4c1d-82df-7d6ed16e8920">

Showing original xhtml has no problem.

<img width="1624" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/dbb79801-0c03-4ff1-aac1-7a20a07a7c54">

Is it a bug on vivliostyle? If not , plz close it.(if it is bug on Chrome, I will be report for them 👍 )

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version 113.0.5672.126

**Additional context**

It looks height becomes half of expected size.

This is container of the element size.
<img width="1624" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/b28a61f8-8ca1-4e0b-94c0-e136f484cae2">

and this is page element size.
<img width="1624" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/0425347e-d1f6-4734-93c7-4bbdb1e4aa2d">

**Comment by MurakamiShinyu** [comment]
@pastak Thanks for reporting the bug.

I confirmed the problem and found that this is a side effect of:

- https://github.com/vivliostyle/vivliostyle.js/pull/1079

The problem does not occur when `&pixelRatio=0` (disable pixel ratio emulation) is specified:

https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/pastak/f21d60c94d787b3a931a4967f332d997/raw/58be6f9c8fb4308998d7473b11e2efa35cf1f461/vivliostyle-testcase.xhtml&pixelRatio=0

**Comment by pastak** [comment]
@MurakamiShinyu Thanks for response.

`&pixelRatio=0` looks to solve this problem but I face another bug. This is test case html: https://gist.github.com/pastak/f21d60c94d787b3a931a4967f332d997#file-case2-xhtml

and loading with vivlioviewer: https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/pastak/f21d60c94d787b3a931a4967f332d997/raw/7a9ae6ac08e0b015253b7b72aa4b8012ab68c59c/case2.xhtml&pixelRatio=0

It is rendered as 1 page on Safari( it is expected )

<img width="1520" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/d30e6bd7-fb5f-42aa-bac6-df119fc1ba2b">

but 2 pages on Chrome.

<img width="1505" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/191533/f90f122a-4535-46d3-bcf0-7a952f39c438">

**Comment by MurakamiShinyu** [comment]
This problem occurs because when the height is auto or percentage value on the element in orthogonal flow (vertical writing mode inside horizontal writing mode), the height cannot be resolved and a fallback size is used, and this fallback size is not very good and causes overflow/page-breaking.

About orthogonal flows, see the spec: https://www.w3.org/TR/css-writing-modes-3/#orthogonal-flows

To avoid this problem, set inline-size (=height in this case) with non-auto and non-percentage value. vh/vw units are ok. e.g.,

```html
<body>
<div style="height: 100vh; writing-mode: vertical-rl;">
    <p>いろはにほへとちりぬるをわかよたれそつねならむ</p>
    <p style="text-align: right;">うゐのおくやまけふこえてあさきゆめみしゑひもせすん</p>
</div>
</body>
```

```html
<body>
<div style="height: max-content; writing-mode: vertical-rl;">
    <p>いろはにほへとちりぬるをわかよたれそつねならむ</p>
    <p style="text-align: right;">うゐのおくやまけふこえてあさきゆめみしゑひもせすん</p>
</div>
</body>
```

**Comment by pastak** [comment]
We solve all problem about this. Thanks 😄 

note: We set `height: 100vh` then no need setting `pixelRatio=0` to solve it.
