### ISSUE TITLE
Pagination result depends on viewer window width

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1228]
**Describe the bug**
In some cases, the page breaks depend on the width and height of the browser window in which Vivliostyle is run, although the page size is set in an @page rule.

**To Reproduce**
1. Paginate the attached file "pagination_bug.html" with Vivliostyle. To reproduce the bug, it is fine to simply paste it into the input field of the Vivliostyle viewer (https://vivliostyle.org/viewer/)
2. Vary the width and the height of the browser window and reload the page

**Expected behavior**
The page breaks should be independent of the browser window size.

**Actual behavior**
Dependent on the browser window size, one can achieve one of two pagination results:
a) The first page contains four headlines and five paragraphs (correct, see screenshot "correct.png")
b) The first page only consists of two headlines (wrong, see screenshot "wrong.png")
I have not discovered a pattern. Sometimes smaller browser window sizes induce the wrong behaviour and sometimes larger ones.

**Desktop (please complete the following information):**
 - macOS Ventura 13.6
 - Safari 17.0 and Chrome 118
 - Vivliostyle 2.25.6

[pagination_bug.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/12929491/pagination_bug.html.zip)

**Correct page breaks:**

<img width="1625" alt="correct" src="https://github.com/vivliostyle/vivliostyle.js/assets/207403/535803da-cf0c-497c-98a7-c495ec4d6fc8">

**Wrong page breaks:**

<img width="1175" alt="wrong" src="https://github.com/vivliostyle/vivliostyle.js/assets/207403/d122b8ed-43c8-4810-b8b2-66d03fde8bd2">

**Comment by MurakamiShinyu** [comment]
@depth42 Thanks for reporting the bug! I am going to fix it.

**Comment by MurakamiShinyu** [comment]
@depth42 
Fixed the bug in PR #1230.

You can test it with the canary version of Vivliostyle Viewer:
https://vivliostyle.vercel.app/

Thanks!

**Comment by depth42** [comment]
Thank you, it works perfect now in the canary viewer! When will the fix be included in the next release? Or is there a way for me to build vivliostyle-print from the current master head of vivliostyle.js?

**Comment by MurakamiShinyu** [comment]
@depth42 Now released! https://www.npmjs.com/package/@vivliostyle/print
