### ISSUE TITLE
How do I add border when table is paginated

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1320]
**Describe the bug**
add border when table is paginated

**To Reproduce**
[viewer](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%20%20%3Chead%3E%20%20%20%20%20%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%20%20%20%20%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%20%20%20%20%3Ctitle%3Etable%3C/title%3E%20%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20@page%20%7B%20%20%20%20%20%20%20%20%20size:%20A4%20portrait;%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20.mate-header%20%7B%20%20%20%20%20%20%20%20%20position:%20element(HeaderRunning);%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20.mate-footer%20%7B%20%20%20%20%20%20%20%20%20position:%20element(FooterRunning);%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20.mate-pro%20%7B%20%20%20%20%20%20%20%20%20page:%20matePro;%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20@page%20matePro%20%7B%20%20%20%20%20%20%20%20%20@top-center%20%7B%20%20%20%20%20%20%20%20%20%20%20content:%20element(HeaderRunning);%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20@bottom-right%20%7B%20%20%20%20%20%20%20%20%20%20%20content:%20element(FooterRunning);%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20@bottom-left%20%7B%20%20%20%20%20%20%20%20%20%20%20content:%20counter(page)%20'page,%20total:'%20counter(pages)%20'pages';%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20table%20%7B%20%20%20%20%20%20%20%20%20border-collapse:%20collapse;%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20th,%20%20%20%20%20%20%20td%20%7B%20%20%20%20%20%20%20%20%20font-size:%2012px;%20%20%20%20%20%20%20%20%20border:%203px%20solid%20%23000;%20%20%20%20%20%20%20%20%20padding:%201em;%20%20%20%20%20%20%20%7D%20%20%20%20%20%3C/style%3E%20%20%20%3C/head%3E%20%20%20%20%3Cbody%3E%20%20%20%20%20%3Csection%20class=%22mate-pro%22%3E%20%20%20%20%20%20%20%3Cdiv%20class=%22mate-header%22%3Eheader%3C/div%3E%20%20%20%20%20%20%20%3Cdiv%20class=%22mate-footer%22%3Efooter%3C/div%3E%20%20%20%20%20%20%20%20%3Ctable%3E%20%20%20%20%20%20%20%20%20%3Cthead%3E%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3Etitle1%3C/th%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3Etitle2%3C/th%3E%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%3C/thead%3E%20%20%20%20%20%20%20%20%20%3Ctbody%3E%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3Eplaceholder%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3Eplaceholder%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%3C/tbody%3E%20%20%20%20%20%20%20%3C/table%3E%20%20%20%20%20%3C/section%3E%20%20%20%3C/body%3E%20%3C/html%3E)

[demo.txt](https://github.com/vivliostyle/vivliostyle.js/files/15249860/demo.txt)

![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/f67a5baa-058d-4905-9d26-d183c6a4f67d)

**Comment by MurakamiShinyu** [comment]
This is not a bug. When a page break splits a box, no border is drawn at broken edges by default. To change this behavior, specify `box-decoration-break: clone`. For example,

```css
td {
  box-decoration-break: clone;
}
```

See the spec: https://www.w3.org/TR/css-break-3/#break-decoration

**Comment by EnochGao** [comment]
thanks your answer, I'll try it right away

**Comment by EnochGao** [comment]
I have a few more questions.I set 
![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/59fbc7d9-47a2-4e49-8ef5-748a7b27b44e)
 but it doesn't work. Why？🥺🥺
![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/fe62846b-fefa-498b-af8c-0d1f1f626711)

**Comment by MurakamiShinyu** [comment]
`position: element(X)` should be corrected to `position: running(X)`. 

See the spec: https://drafts.csswg.org/css-gcpm/#running-syntax

**Comment by EnochGao** [comment]
> `position: element(X)` should be corrected to `position: running(X)`.
> 
> See the spec: https://drafts.csswg.org/css-gcpm/#running-syntax

Oh, I'm so stupid.😅😅😅 You told me before. I made a mistake again. Thank you very much for your answer
