### ISSUE TITLE
Complex running title, page number is incorrect after resetting page number

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1325]
**Describe the bug**
Some complex headers and footers use page numbers, after reset, the subsequent page numbers will be wrong

**To Reproduce**
<img width="1019" alt="image" src="https://github.com/vivliostyle/vivliostyle.js/assets/41459067/21391fa2-b2dc-4437-8d89-501f565e83ac">

[demo.txt](https://github.com/vivliostyle/vivliostyle.js/files/15276052/demo.txt)

[online viewer](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3EDocument%3C/title%3E%20%09%09%3Cstyle%3E%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4;%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%09%7D%20%20%09%09%09%09@bottom-center%20%7B%20%09%09%09%09%09content:%20'footer%20pages::'%20counter(page)%20'/'%20counter(pages);%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%09@page%20:nth(2)%20%7B%20%09%09%09%09counter-reset:%20page%201;%20%09%09%09%7D%20%20%09%09%09header%20%7B%20%09%09%09%09position:%20running(HeaderRunning);%20%09%09%09%7D%20%09%09%09.counter::after%20%7B%20%09%09%09%09content:%20'header%20pages::'%20counter(page)%20'/'%20counter(pages);%20%09%09%09%7D%20%20%09%09%3C/style%3E%20%09%3C/head%3E%20%09%3Cbody%3E%20%09%09%3Csection%3E%20%09%09%09%3Cheader%3E%20%09%09%09%09%3Cimg%20src=%22https://placehold.co/200x50%22%20/%3E%20%09%09%09%09%3Cspan%20class=%22counter%22%3E%3C/span%3E%20%09%09%09%09%3Cimg%20src=%22https://placehold.co/200x50%22%20/%3E%20%09%09%09%3C/header%3E%20%09%09%09%3Cdiv%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%20%09%09%09%09%3Cdiv%20class=%22reset-page%22%3Ereset%20page%3C/div%3E%20%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%09%3Cp%3E%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%09placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%09%09%09%09%3C/p%3E%20%09%09%09%3C/div%3E%20%09%09%3C/section%3E%20%09%3C/body%3E%20%3C/html%3E&spread=false)

**Comment by EnochGao** [comment]
and what happens to the total number of pages after the page number is reset

**Comment by MurakamiShinyu** [comment]
Thank you very much for reporting bugs! I will investigate the issue, please wait a moment.

**Comment by EnochGao** [comment]
and target-counter in running element equally incorrect

**Comment by MurakamiShinyu** [comment]
I put test files in my GitHub Gist: https://gist.github.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0

- [issue-1325-running-element-page-number.html](https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-page-number.html)
- [issue-1325-running-element-page-number-2.html](https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-page-number-2.html)
- [issue-1325-running-element-target-counter.html](https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-target-counter.html)

After the fix in #1327, the first and second test results are good:

- https://vivliostyle-6f1aa9qde-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-page-number.html

- https://vivliostyle-6f1aa9qde-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-page-number-2.html

But the result of the 3rd test, with target-counter, still has problem:

- https://vivliostyle-6f1aa9qde-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/7616ab180e72e38addafc1a7ea44d8d0/raw/issue-1325-running-element-target-counter.html

![Screenshot 2024-05-20 13 53 13](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/75ada7f5-0a34-45f2-b9c0-fe3d77e4299f)

**Comment by EnochGao** [comment]
3rd test,in previous versions, using target-counter in the running element would result in '?? Should it be fixed in the same way as page/pages-counter
