### ISSUE TITLE
When a large amount of data is entered into a 'td' cell within a table, exceeding the length of two pages, the table automatically paginates. This results in a blank content area above the table.

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1326]
**Describe the bug**
When a large amount of data is entered into a 'td' cell within a table, exceeding the length of two pages, the table automatically paginates. This results in a blank content area above the table.

**To Reproduce**
[table_bug.txt](https://github.com/vivliostyle/vivliostyle.js/files/15281278/table_bug.txt)
[online viewer](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%20%20%3Chead%3E%20%20%20%20%20%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%20%20%20%20%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%20%20%20%20%3Ctitle%3EDocument%3C/title%3E%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20@page%20%7B%20%20%20%20%20%20%20%20%20size:%20A4;%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20table%20%7B%20%20%20%20%20%20%20%20%20width:%20100%25;%20%20%20%20%20%20%20%20%20border-collapse:%20collapse;%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20td,%20%20%20%20%20%20%20th%20%7B%20%20%20%20%20%20%20%20%20box-decoration-break:%20clone;%20%20%20%20%20%20%20%20%20border:%201px%20solid%20black;%20%20%20%20%20%20%20%7D%20%20%20%20%20%3C/style%3E%20%20%20%3C/head%3E%20%20%20%3Cbody%3E%20%20%20%20%20%3Csection%3E%20%20%20%20%20%20%20%3Cdiv%3Eguide%20guide%20guide%20guide%20guide%3C/div%3E%20%20%20%20%20%20%20%3Ctable%3E%20%20%20%20%20%20%20%20%20%3Cthead%3E%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3E1%3C/th%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3E2%3C/th%3E%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%3C/thead%3E%20%20%20%20%20%20%20%20%20%3Ctbody%3E%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E1%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/p%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/p%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/p%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/p%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%20placeholder%20placeholder%20placeholder%20placeholder%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/p%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%3C/tbody%3E%20%20%20%20%20%20%20%3C/table%3E%20%20%20%20%20%3C/section%3E%20%20%20%3C/body%3E%20%3C/html%3E)
![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/e8e88fe2-5c0b-49db-9337-f67de76d9194)

**Comment by EnochGao** [comment]
This could be a table header related issue
[table_bug.txt](https://github.com/vivliostyle/vivliostyle.js/files/15399932/table_bug.txt)
![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/8fdfec24-a7b6-4e10-b6cf-316f11d68b2a)
![image](https://github.com/vivliostyle/vivliostyle.js/assets/41459067/ebc0bc22-82cf-4c1c-983f-e90f77053dad)

**Comment by EnochGao** [comment]
I found that for the time being you can set the display property to simulate the table
[pseudo_table.txt](https://github.com/vivliostyle/vivliostyle.js/files/15465309/pseudo_table.txt)

**Comment by MurakamiShinyu** [comment]
I made a simple test case.

https://gist.github.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6#file-table-break-1-html

Test with Vivliostyle Viewer:
 
 - https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-1.html



I think I can fix it today.

**Comment by EnochGao** [comment]
Hi, Shinyu, how is the progress coming along?

**Comment by MurakamiShinyu** [comment]
Hi, I'm still debugging it.

It seems the overflow checking has problem when table or table-cell has border and paddings.

https://github.com/vivliostyle/vivliostyle.js/blob/20fee03dd00c1be0898671c9fef94eb7260751ee/packages/core/src/vivliostyle/layout.ts#L2578-L2598

**Comment by MurakamiShinyu** [comment]
I found that the problem does not seem so simple. This problem happens even when the table has no border and padding. I made some simplified test cases. 

- https://gist.github.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6#file-table-break-4-3-html
  - with viewer: https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-4-3.html
- https://gist.github.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6#file-table-break-5-2-html
  - with viewer: https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-5-2.html

**Comment by MurakamiShinyu** [comment]
Found bug:

https://github.com/vivliostyle/vivliostyle.js/blob/20fee03dd00c1be0898671c9fef94eb7260751ee/packages/core/src/vivliostyle/table.ts#L113-L123

This does not work as expected when the `verticalAlign` value is `"inherit"` which is the default setting for table cells in the `UserAgentBaseCss`:

https://github.com/vivliostyle/vivliostyle.js/blob/20fee03dd00c1be0898671c9fef94eb7260751ee/packages/core/src/vivliostyle/assets.ts#L1197-L1201

To fix this, `if (verticalAlign === "middle" || verticalAlign === "bottom")` should be corrected to `if (verticalAlign !== "top" && verticalAlign !== "baseline")`.

However, the case in https://github.com/vivliostyle/vivliostyle.js/issues/1326#issuecomment-2134539771 is not resolved in this fix.

**Comment by EnochGao** [comment]
@MurakamiShinyu Ha ha, a major breakthrough!! Thanks for your hard work.

**Comment by MurakamiShinyu** [comment]
Fixed in #1339.

Tests:

- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table_bug.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table_bug2.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-1.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-2.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-3.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-4-1.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-4-2.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-4-3.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-5-1.html
- https://vivliostyle-git-fix-issue1326-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6/raw/table-break-5-2.html

(GitHub Gist: https://gist.github.com/MurakamiShinyu/22585fe8c74d2114477117d7d2cd0ff6)

**Comment by jiang0112** [comment]
When a large amount of data is entered into "td" cells within a table, several special cases emerge after pagination: the data does not start from the top, giving rise to regions devoid of content.
![iwEcAqNwbmcDAQTRAqUF0QMoBrCZrHRLDkeCJQZUmbn_Rd8AB9IZjKU6CAAJomltCgAL0gAAtIc png_720x720q90](https://github.com/vivliostyle/vivliostyle.js/assets/56588176/ab4e1707-b6e6-47f0-b21f-55c74cdd9231)

[min.txt](https://github.com/user-attachments/files/15802962/min.txt)

**Comment by jiang0112** [comment]
@MurakamiShinyu

**Comment by MurakamiShinyu** [comment]
@jiang0112 Please open a new issue to report a new problem.
