### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by jiang0112** [vivliostyle/vivliostyle.js#1329]
When applying the CSS styles with double underscores, specifically text-decoration-line: underline;, text-decoration-style: double;, and text-decoration-style: under;, the two lines appear to merge into one.The documentation indeed supports these properties.

[bug](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3Etable%3C/title%3E%20%09%09%3Cscript%20src=%22../../../dist/paged.polyfill.js%22%3E%3C/script%3E%20%20%09%09%3Cstyle%3E%20%09%09%09.base-footer%20%7B%20%09%09%09%09text-transform:%20uppercasse;%20%09%09%09%09font-size:%2012px;%20%09%09%09%7D%20%20%09%09%09.base-header%20%7B%20%09%09%09%09height:%20100px;%20%09%09%09%09text-align:%20start;%20%09%09%09%09position:%20relative;%20%09%09%09%7D%20%20%09%09%09.base-title%20%7B%20%09%09%09%09position:%20absolute;%20%09%09%09%09left:%20295px;%20%09%09%09%09top:%2038px;%20%09%09%09%09font-size:%2016px;%20%09%09%09%09font-weight:%20500;%20%09%09%09%09line-height:%2019px;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20%7B%20%09%09%09%09width:%20100%25;%20%09%09%09%09border-collapse:%20collapse;%20%09%09%09%09border:%201px%20solid%20%23dcdcdc;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20thead%20tr%20%7B%20%09%09%09%09background:%20%23ebedf1;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20thead%20tr%20th%20%7B%20%09%09%09%09text-align:%20center;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20tr,%20%09%09%09.base-evaluation%20td%20%7B%20%09%09%09%09break-inside:%20avoid;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20th,%20%09%09%09.base-evaluation%20td%20%7B%20%09%09%09%09font-size:%2012px;%20%09%09%09%09/*%20border:%201px%20solid%20%23dcdcdc;%20*/%20%09%09%09%09padding:%201em;%20%09%09%09%7D%20%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4%20portrait;%20%09%09%09%09margin:%2030px;%20%09%09%09%09margin-top:%20130px;%20%09%09%09%7D%20%20%09%09%09.mate-pro%20%7B%20%09%09%09%09page:%20matePro;%20%09%09%09%7D%20%20%09%09%09.mate-pro-header%20%7B%20%09%09%09%09position:%20running(mateproHeaderRunning);%20%09%09%09%7D%20%20%09%09%09.mate-pro-footer%20%7B%20%09%09%09%09position:%20running(mateproFooterRunning);%20%09%09%09%7D%20%09%09%09.imgSmall%7B%20%09%09%09%09width:180px;%20%7D%20%09%09.imgSmall%3Eimg%7B%20display:%20block%20!important;%20%20%20%20%20%20%20%20%20%20%20width:%20100%25;%20%20%20%20%20%20%20%20%20%20%20height:%20100%25;%20%20%20%20%20%20%20%20%20%20%20object-fit:%20contain;%20%7D%20.underline%7B%20%09%09%09text-decoration-line:%20underline;%20%20%20%20%20%20%20%20%20%20%20text-decoration-style:%20double;%20%09%09%20%20font-family:%20Arial,%20Arial;%20%20%20%20%20%20%20%20%20%20%20font-weight:%20bold;%20%20%20%20%20%20%20%20%20%20%20font-size:%2022px;%20%09%09%20%20text-underline-position:%20under;%20%7D%20%09%09%09@page%20matePro%20%7B%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(mateproHeaderRunning);%20%09%09%09%09%7D%20%20%09%09%09%09@bottom-center%20%7B%20%09%09%09%09%09content:%20element(mateproFooterRunning);%20%09%09%09%09%7D%20%20%09%09%09%09@bottom-left%20%7B%20%09%09%09%09%09content:%20counter(page)%20'page,%20total:'%20counter(pages)%20'pages';%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%3C/style%3E%20%09%3C/head%3E%20%20%09%3Cbody%3E%20%09%09%3Csection%20class=%22mate-pro%22%3E%20%09%09%09%3Cheader%20class=%22base-header%20mate-pro-header%22%3E%20%09%09%09%09%3Cspan%20class=%22base-title%22%3EHUAWEI%20Mate%2060%20Pro%3C/span%3E%20%09%09%09%3C/header%3E%20%20%09%09%09%3Cfooter%20class=%22base-footer%20mate-pro-footer%22%3Efooter%20mate%2060%20pro%3C/footer%3E%20%09%09%20%09%09%09%3Cdiv%20class=%22underline%22%3Eabcdefghijklmnop%3C/div%3E%20%20%3C/html%3E)

[code.txt](https://github.com/vivliostyle/vivliostyle.js/files/15288475/code.txt)
![image](https://github.com/vivliostyle/vivliostyle.js/assets/56588176/673fdbc9-97cf-471d-8a04-3ef0673f2c59)
![image](https://github.com/vivliostyle/vivliostyle.js/assets/56588176/3dc7cf4b-48bd-4139-87a3-1d71c94845eb)

**Comment by depth42** [comment]
Just some thoughts: The mentioned problem does only seem to occur with Chrome not with Safari. However, I have been using Vivliostyle in a WKWebView on iOS, which is basically a Safari view inside an app. With it, I have been paginating HTML documents and converted them to PDFs. In this process, there are a **lot** of rounding / pixel-snapping errors with text underlines similar to the reported issue. The only way I could find to work around them is to blow up the scaling in Vivliostyle to 400% and to then scale the PDFs back down. It seems like the Chrome and Safari engines don't have a very precise model for underlines.

**Comment by MurakamiShinyu** [comment]
I investigated this issue and found that the problem is caused by Chrome (Chromium)'s rendering of `text-decoration-style: double` where the distance of the two lines depends on the device pixel size (= 1px / window.devicePixelRatio) which is equal to the minimum border line width. Current Vivliostyle.js implementation uses a hack emulating very high pixel ratio to enable very thin border width on PDF output. See:

- https://github.com/vivliostyle/vivliostyle.js/pull/1079

> The output pixel ratio is configurable by setting `pixelRatio=<number>` in [Vivliostyle Viewer options](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/viewer/src/models/viewer-options.ts), or in the [CoreViewerOptions](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/core/src/vivliostyle/core-viewer.ts#L73). The default setting is `pixelRatio=8`, which means that the minimum border width is 1/8 px = 0.125px (about 0.09pt, or 0.033mm).

As a result, the distance of the two lines of double underline becomes 1/8 px = 0.125px, which is too small and the gap is almost invisible.

Possible workarounds will be:

- specify `pixelRatio=0` to disable the high pixel ratio emulation and use the default browser rendering
  - [test](https://vivliostyle.org/viewer/#src=data:,%3Cstyle%3E%20.underline%7B%20%20%20text-decoration-line:%20underline;%20%20%20text-decoration-style:%20double;%20%20%20font-family:%20Arial,%20Arial;%20%20%20font-weight:%20bold;%20%20%20font-size:%2022px;%20%20%20text-underline-position:%20under;%20%7D%20%3C/style%3E%20%3Cdiv%20class=%22underline%22%3Eabcdefghijklmnop%3C/div%3E&pixelRatio=0)
- or, use `border-bottom-style: double` instead of `text-decoration-style: double`

**Comment by jiang0112** [comment]
Thanks for your reply, the problem is solved
