### ISSUE TITLE
Is the input HTML document required to be formatted?

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1345]
**Describe the bug**
I'm not sure if this is a bug, but when the same file is processed, one version is minified and the other is formatted; the minified file results in errors.

[minified ](https://vivliostyle.org/viewer/#src=https://gist.github.com/EnochGao/bc987146fbba904be3ca94a1c7282f45&bookMode=false&spread=false)
[formatted](https://vivliostyle.org/viewer/#src=https://gist.github.com/EnochGao/d7a6e3202a07b38612e95cb55dcd8c16&bookMode=false&spread=false)

**Comment by EnochGao** [comment]
I found that formatting using prettiter is normal, but formatting inside vscode is not

https://github.com/vivliostyle/vivliostyle.js/assets/41459067/b53559e4-8457-4e4a-a659-d8325c03d533

**Comment by EnochGao** [comment]
I find it normal to remove all comment nodes.` html = html.replace(/<!---->/g, ' ')`

**Comment by MurakamiShinyu** [comment]
The results must not vary depending on whether the HTML code is formatted or not, or whether there are comments or not. If it changes the result or causes errors, it is an obvious bug.

The error "InvalidNodeTypeError: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent." occurs in https://github.com/vivliostyle/vivliostyle.js/blob/926b6fe41eebec9b6b2ba971e49ec7e423127779/packages/core/src/vivliostyle/layout.ts#L2102 where the `node` must have parent node but does not.

**Comment by MurakamiShinyu** [comment]
I found that this error occurs with simple cases where a table cell contains some long text which spans multipe pages and an empty element.

This is a regression bug in v2.30.0 and the previous versions do not have this problem.

Examples:
  - [table-1](https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-1.html)
    - test with Vivliostyle Viewer v2.30.0:
      https://vivliostyle.github.io/viewer/v2.30.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-1.html
    - test with Vivliostyle Viewer v2.29.0:
      https://vivliostyle.github.io/viewer/v2.29.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-1.html
  - [table-2](https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-2.html)
    - test with Vivliostyle Viewer v2.30.0:
      https://vivliostyle.github.io/viewer/v2.30.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-2.html
    - test with Vivliostyle Viewer v2.29.0:
      https://vivliostyle.github.io/viewer/v2.29.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-2.html

**Comment by MurakamiShinyu** [comment]
Fixed in PR #1347.

Test:
- https://vivliostyle-git-fix-issue1345-vivliostyle.vercel.app/#src=https://gist.github.com/EnochGao/bc987146fbba904be3ca94a1c7282f45
- https://vivliostyle-git-fix-issue1345-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-1.html
- https://vivliostyle-git-fix-issue1345-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/fd6934f9b6760781ee997931d161b145/raw/table-2.html
