### ISSUE TITLE
When a large amount of data is entered into "td" cells within a table, several special cases emerge after pagination: the data does not start from the top, giving rise to regions devoid of content.

### ISSUE THREAD

**Issue by jiang0112** [vivliostyle/vivliostyle.js#1346]
When a large amount of data is entered into "td" cells within a table, several special cases emerge after pagination: the data does not start from the top, giving rise to regions devoid of content.
![iwEcAqNwbmcDAQTRAqUF0QMoBrCZrHRLDkeCJQZUmbn_Rd8AB9IZjKU6CAAJomltCgAL0gAAtIc png_720x720q90](https://github.com/vivliostyle/vivliostyle.js/assets/56588176/ab4e1707-b6e6-47f0-b21f-55c74cdd9231)

[min.txt](https://github.com/user-attachments/files/15802962/min.txt)

_Originally posted by @jiang0112 in https://github.com/vivliostyle/vivliostyle.js/issues/1326#issuecomment-2162634861_

**Comment by MurakamiShinyu** [comment]
The table cell content is vertically center-aligned by default. Adding the following style will solve this problem:

```css
td {
  vertical-align: top;
}
```

Test: https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/MurakamiShinyu/d7b9c81ed08a40c0061a51baa318da57/raw/2ffc1a7b7c9026b3bfb4c41f3d57a1751382f34b/min.html&style=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0Atd%20%7B%0A%20%20vertical-align:%20top;%0A%7D
