### ISSUE TITLE
@media定義を含むCSSで、その下のCSSがプレビューに反映されない？

### ISSUE THREAD

**Issue by Yuki-book** [vivliostyle/vivliostyle.js#1360]
Vivliostyle初心者です。
Vivliostyleが@mediaをサポートしているのかわかっておりません。

CSSに@media定義を含むと、その下のCSSがプレビューに反映されない現象が発生しました。
@mediaが未サポートとしても、読み飛ばすような仕様にはならないでしょうか？

vivliostyle --versionは、以下です。
cli: 8.12.1
core: 2.30.1

# 現象の説明

## 構成ファイル

test.htmlとmystyle.cssで構成しています。
[test01.zip](https://github.com/user-attachments/files/16117691/test01.zip)

【test.html】

```
<div class="idxtab">
<p class="head">数</p>
<table>
<tr><th>4004</th></tr>
<tr><th>　　インテル社  </th>   <td>2.2  　</td></tr>
</table>
</div>
```

【test.html】

```
table { 通常のテーブル定義
}

p.bold {
   @media amzn-kf8  {
     font-weight: normal;
   }
   font-weight: bold;
}

div.idxtab table {
        索引用のテーブル定義
}

```

## プレビュー（@mediaあり）

vivliostyle previewコマンドでプレビューすると以下のように表示します。

![view_ng](https://github.com/vivliostyle/vivliostyle-cli/assets/46343265/98a6e5a4-1697-426c-83aa-276fb25b235c)

@media 以下の「div.idxtab table」のCSSが有効になっていないように見えます。
（通常のテーブル定義で表示している）

## プレビュー（@mediaなし）

mystyle.cssの@mediaをコメントアウトすると、意図した表示になります。

![view_ok](https://github.com/vivliostyle/vivliostyle-cli/assets/46343265/343acdac-38a2-4b78-a88b-5bd4062581c6)

# 希望する仕様

この現象は、KindleのEPUB原稿を流用してVivliostyleでプレビューした際に遭遇しました。

@mediaが未サポートとしても、読み飛ばすような仕様にはならないでしょうか？

以上、よろしくお願い致します。

**Comment by MurakamiShinyu** [comment]
@Yuki-book さん、バグ報告ありがとうございます。

これはCLIではなくてVivliostyle.jsの問題なので、Vivliostyle.jsのissueに移動しました。

まず、Vivliostyleが `@media` をサポートしているかですが、限定的にサポートしています。ドキュメント：

https://docs.vivliostyle.org/#/supported-css-features#media-queries

> **Media queries**
>
> - Vivliostyle uses styles specified for `print` media  (as well as `all`).
>   - Vivliostyle specific media type `vivliostyle` is enabled in addition to print media.
> - Supported media features
>   - (min-|max-)width 
>   - (min-|max-)height 
>   - (min-|max-)device-width 
>   - (min-|max-)device-height 
>   - (min-|max-)color 

そして、サポートしていないMediaクエリーはそのルールを読み飛ばす仕様です。そうならなければ、バグです。

問題が起きているCSSコードですが、スタイルルールの中に `@media {…}` が書かれています。

```css
p.bold {
   @media amzn-kf8  {
     font-weight: normal;
   }
   font-weight: bold;
}
```

これは、最近のブラウザでサポートされたCSS Nestingの構文です。 

- Spec: https://drafts.csswg.org/css-nesting/#conditionals

Vivliostyle.jsはこのCSS Nestingをサポートしていません。 

- Issue: https://github.com/vivliostyle/vivliostyle.js/issues/1032

サポートしてないCSSルールは読み飛ばす仕様のはずなのに、内部でエラーが発生してこの不具合が起きていることがわかりました。これはバグですので修正します。

この問題が解決されるまでの間、`@media` ルールを外に出して、ネストしないようにしてください。

```css
p.bold {
  font-weight: bold;
}

@media amzn-kf8 {
  p.bold {
    font-weight: normal;
  }
}
```

このように書けば、問題なく処理されて `@media amzn-kf8 {…}` のルールだけ無視されるはずです。

**Comment by Yuki-book** [comment]
CLIとVivliostyle.jsの問題点の切り分けが間違っており申し訳ありませんでした。
Vivliostyleについて、学んでいきたいと思います。

さて、CSSでネスティングした@mediaについて丁寧に解説していただき、ありがとうございます。CSSは、奥が深いですね。

教えていただいた回避策で問題点は解決しました。
ありがとうございました。
