### ISSUE TITLE
CSS counter-reset works differently from browsers.

### ISSUE THREAD

**Issue by yamahige** [vivliostyle/vivliostyle.js#1389]
**Describe the bug**
when `counter-reset` in the top level of numbered list, Vivliostyle seems to keep the counter value from previous sibling, and create a new counter of the same name.
Browsers reset the counter value.

**To Reproduce**
Samples use `counters()` function.
<https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/yamahige/48634750245ca0d25afca97b26d4a5a7/raw/78debaef61085deb56e708769676c101c74950e8/list-counter-share.html>

**Expected behavior**
I'm not sure with the counter-reset specifications...

**Desktop (please complete the following information):**
 - Browser: Chrome, Safari, Firefox, Edge
 - OS: macOS

**Screenshots**
Vivliostyle:
![Vivliostyle](https://github.com/user-attachments/assets/5e065c30-ee57-48d9-9615-9091d73c39de)
Chrome browser:
![Chrome-browser](https://github.com/user-attachments/assets/7c692fbc-76ce-46d3-ad13-ce83158abc30)
Safari:
<img width="547" alt="Safari" src="https://github.com/user-attachments/assets/9bd4166b-4571-4a94-a220-3e09b71a939b">
Firefox:
<img width="620" alt="Firefox" src="https://github.com/user-attachments/assets/8bc62c05-0b6a-48d4-a3d2-e5071f4d41ee">
Edge:
<img width="583" alt="Edge" src="https://github.com/user-attachments/assets/074e863d-1cc9-4b9a-a3be-a2d7abf5e7e8">

**Comment by yamahige** [comment]
Additionally, behaves differently for `counter-set`. I'll open another issue for that.

**Comment by MurakamiShinyu** [comment]
The spec https://drafts.csswg.org/css2/#scope says:

> The **scope** of a counter starts at the first element in the document that has a `counter-reset` for that counter and includes the element’s descendants and its following siblings with their descendants. However, it does not include any elements in the scope of a counter with the same name created by a `counter-reset` on a later sibling of the element or by a later `counter-reset` on the same element.

It seems that "However, ..." in this spec is not correctly implemented in Vivliostyle.js.

**Comment by MurakamiShinyu** [comment]
Fixed in PR #1398.

Test: https://vivliostyle-git-fix-issue1389-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/yamahige/48634750245ca0d25afca97b26d4a5a7/raw/78debaef61085deb56e708769676c101c74950e8/list-counter-share.html

Screenshot:
![Screenshot 2024-10-18 16 59 39](https://github.com/user-attachments/assets/8580bc2c-1c24-45b9-9b0a-f1f5225efab2)
