### ISSUE TITLE
Broken text layout at page break when ruby-text font size is larger than usual

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1401]
[公式サンプル](https://vivliostyle.org/ja/samples/)の『銀河鉄道の夜』を閲覧したとき、何らかの条件によって、改ページされるところで文字間が異常に開く、あるいは一文字だけの行ができるといったテキストレイアウトの異常が発生することがあります。再現する条件を調べたところ、Chromeの「設定」→「デザイン」→「フォントをカスタマイズ」の「最小フォントサイズ」を9以上の値にするとこの現象が起きました。

テスト：
https://vivliostyle.org/viewer/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gingatetsudo/index.html

**追記：最小フォントサイズ設定をしなくても、CSSでルビのフォントサイズを大きめに指定すると再現します。以下はルビのフォントサイズを11pxに指定したテスト：**

https://vivliostyle.org/viewer/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gingatetsudo/index.html&style=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0Aruby%3Ert%7Bfont-size:11px%7D

スクリーンショット：

![Screenshot 2024-10-24 12 06 19](https://github.com/user-attachments/assets/6d0e0e87-2fc4-46cf-8310-179461e938d7)

![Screenshot 2024-10-24 12 06 42](https://github.com/user-attachments/assets/aea14ffa-41f8-4c72-9173-57fc9f16d21b)

![Screenshot 2024-10-24 12 07 15](https://github.com/user-attachments/assets/78eda799-d224-4856-b5cd-efdba3bcff12)

![Screenshot 2024-10-24 12 07 33](https://github.com/user-attachments/assets/16d450fc-948b-454b-a921-2088f7131c2f)

**Comment by skmtjny** [comment]
@MurakamiShinyu 

インラインでSVGを挿入した際にも似た現象が発生していたのでお知らせします。

![image](https://github.com/user-attachments/assets/8e67f19b-9196-408c-a9af-8e1f77cebe3c)
[241025.zip](https://github.com/user-attachments/files/17519410/241025.zip)

**Comment by MurakamiShinyu** [comment]
@skmtjny 
> インラインでSVGを挿入した際にも似た現象が発生していたのでお知らせします。

ありがとうございます。調べます

**Comment by MurakamiShinyu** [comment]
ルビによって起きる不具合は [v2.30.0](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.0) での次の修正に問題があったためでした：

- PR #1333

これについては、 PR #1404 でのとりあえずの修正 2bb4d0e2343734421f5082849e692d17846b4eee で解決します。

しかし、 https://github.com/vivliostyle/vivliostyle.js/issues/1401#issuecomment-2437298647 で報告をもらったインラインSVGでの不具合は、別の原因のようです。
[v2.19.2](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.19.2) での次の修正に問題があるようです。（この修正をする前のものでは問題が起きない）

- PR #1037

この修正を見直します。

**Comment by MurakamiShinyu** [comment]
インラインSVGでの不具合は別の原因なので、新しいissueに分けました:

- #1406

**Comment by MurakamiShinyu** [comment]
Fixed in #1404.

Test: https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gingatetsudo/index.html&style=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0Aruby%3Ert%7Bfont-size:11px%7D

**Comment by skmtjny** [comment]
@MurakamiShinyu さま

確かなことはいえませんが、いくつかテストしてみた範囲では
rubyが連続する場合では不具合が残っているような感じがします。
![image](https://github.com/user-attachments/assets/eccac05e-2089-49c0-88a4-d6c861516597)

[241125.zip](https://github.com/user-attachments/files/17897155/241125.zip)

**Comment by MurakamiShinyu** [comment]
ルビだけの問題ではなくて、行の途中に前方（block-start側）にはみ出しているインライン要素があって、そのインライン要素だけがページ/段の終わりに収まる位置にあるという条件で発生している不具合でした。

`<span style="vertical-align: 2rem; font-size: 0.33em">くけこ</span>` というインライン要素によってこれが起きる例：

https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401c1.html

Test: https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401c1.html

Screenshot:
![Screenshot 2024-11-27 10 27 29](https://github.com/user-attachments/assets/6782a599-527b-4aab-8b1d-617b3d2284fe)

**Comment by MurakamiShinyu** [comment]
PR #1424 で修正しました。

テスト：
- https://vivliostyle-git-fix-bug-at-break-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241125.html
- https://vivliostyle-git-fix-bug-at-break-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401c1.html

**Comment by skmtjny** [comment]
@MurakamiShinyu さま
修正ありがとうございます。

テストしていたところ、崩れが発生するケース、しないケースが見られたため
いくつかサンプルを作ってみました。

影響を与える要素としては確認できたのは以下です。
・rubyタグの連続
・rubyタグが設定されている文字の位置
・rbタグの有無
・段落の文字数

他にもあるかもしれませんが取り急ぎサンプルデータをお送りします。

[241202.zip](https://github.com/user-attachments/files/17975115/241202.zip)

**Comment by MurakamiShinyu** [comment]
@skmtjny 調査ありがとうございます。修正がまだ不十分でした。issue再々オープンします。

**Comment by MurakamiShinyu** [comment]
Fixed in #1426.

Test:
- https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241202-01.html
- https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241202-02.html
- https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241202-03.html
- https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241202-04.html
- https://vivliostyle-git-fix-issue1401-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1401-241202-05.html
