### ISSUE TITLE
Broken text layout at page/column break caused by inline SVG

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1406]
Issue #1401 のコメント https://github.com/vivliostyle/vivliostyle.js/issues/1401#issuecomment-2437266565 で報告された不具合ですが、 #1401 とは別な原因によるものなので新しいissueにします。 (thanks @skmtjny):

> インラインでSVGを挿入した際にも似た現象が発生していたのでお知らせします。
> 
> ![image](https://github.com/user-attachments/assets/8e67f19b-9196-408c-a9af-8e1f77cebe3c)
> [241025.zip](https://github.com/user-attachments/files/17519410/241025.zip)

https://github.com/vivliostyle/vivliostyle.js/issues/1401#issuecomment-2437524528:
> https://github.com/vivliostyle/vivliostyle.js/issues/1401#issuecomment-2437298647 で報告をもらったインラインSVGでの不具合は、別の原因のようです。
> [v2.19.2](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.19.2) での次の修正に問題があるようです。（この修正をする前のものでは問題が起きない）
> 
> - PR #1037
> 
> この修正を見直します。
>

**Comment by MurakamiShinyu** [comment]
Fixed in #1407.

Test: https://vivliostyle-git-fix-issue1406-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/svgtest1.html

**Comment by skmtjny** [comment]
@MurakamiShinyu 
改修ありがとうございました。
ご対応頂いたおかげでかなり改善されていたのですが、
まだいくつか崩れる場面が見られました。

ケース1　先頭の文字が2回表示される
![image](https://github.com/user-attachments/assets/eb475841-8d0e-45a8-8b28-d0d78915f9d9)

ケース2　SVGの表示が崩れる
![image](https://github.com/user-attachments/assets/4dbb3400-559d-47f5-92df-3cfcbc55796c)

[241122.zip](https://github.com/user-attachments/files/17853776/241122.zip)

新しくissueを起こすべきか迷いましたが
いったんこちらに報告させていただきます。

**Comment by MurakamiShinyu** [comment]
@skmtjny 報告ありがとうございます。修正が不完全だったようなので再オープンします。

**Comment by MurakamiShinyu** [comment]
PR #1424 で修正しました。

テスト：
- https://vivliostyle-git-fix-bug-at-break-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/b496dbc2a0e181f34f5ab740f80249b7/raw/test1406-241122.html
