### ISSUE TITLE
Building vivliostyle-print fails with an error

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1421]
**Describe the bug**
With the current version of vivliostyle.js, building vivliostyle-print is failing with an error.

**To Reproduce**
Perform the default instructions for building vivliostyle-print:

git clone https://github.com/vivliostyle/vivliostyle-print.git
cd vivliostyle-print
npm install
npm run build_demo

**Expected behavior**
The build should succeed without an error.

**Actual behavior**
The build fails with the following error:

[!] Error: 'printHTML' is not exported by node_modules/@vivliostyle/core/lib/vivliostyle.js, imported by src/index.js

**Desktop**
 - macOS 15.1

**Comment by MurakamiShinyu** [comment]
Hi, I am working on fixing it.

I replaced the bundler tool for `@vivliostyle/core` from microbundle to esbuild (https://github.com/vivliostyle/vivliostyle.js/pull/1417), with same output format option (--format=cjs). However, it seems that the esbuild output JS code with cjs format cannot be handled with the current bundler (rollup v2) used for vivliostyle-print. I am testing the latest rollup (v4) and it is working.

**Comment by depth42** [comment]
Great, thanks! It's working fine now.
