### ISSUE TITLE
Add support for Compositing and Blending Level 1

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle.js#148]
https://drafts.fxtf.org/compositing-1/

Should be easy to support by simply delegating to the browser. There's no particular interaction with pagination.

Note that 2 properties (isolation and mix-blend-mode) create stacking context when not at their initial value. I'm marking this as quickfix assuming we can simply pass everything through, but if the stacking context story complicates things, we should probably split this bug in 2, one for background-blend-mode, which should stay a quickfix, and one for isolation and mix-blend-mode.

**Comment by kwkbtr** [comment]
Since the current implementation does nothing special about stacking context, I made those properties to be simply delegated to the browser.
