### ISSUE TITLE
Add support for font-feature-settings

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle.js#151]
https://drafts.csswg.org/css-fonts-3/#propdef-font-feature-settings

Should be possible to simply pass through to the browser, making it easy to implement.

**Comment by kwkbtr** [comment]
Since `font-feature-settings` is inherited, it should be added to [`adapt.csscasc.inheritedProps`](https://github.com/vivliostyle/vivliostyle.js/blob/fa4f987e0f877af8cb32e60729ba81696bf6d0ca/src/adapt/csscasc.js#L18-L74). @skoji
