### ISSUE TITLE
box-shadow/text-shadow is ignored

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#156]
box-shadow and text-shadow are in the [supported features](http://vivliostyle.com/en/documentation/supported-features/) as  "Support depends on browser capabilities", however it seems ignored.

Test
http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://rawgit.com/zopyx/css-paged-media-tutorial/master/lesson-box-styling/index.html

**Comment by kwkbtr** [comment]
It seems that we need to fix the parser for validators (defined in [`validation.txt`](https://github.com/vivliostyle/vivliostyle.js/blob/master/resources/validation.txt)).
Specifically, [this line](https://github.com/vivliostyle/vivliostyle.js/blob/7041283ed326611517bafd7e7da56845f2eecf47/src/adapt/cssvalid.js#L1987) should be fixed, for values for shadows are comma-separated lists, not space-separated lists.
