### ISSUE TITLE
Incorrect pagination caused by absolutely positioned element

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#158]
Current implementation delays application of `position: relative` after the page layout is done:
- https://github.com/vivliostyle/vivliostyle.js/blob/c30d5972cf0ae6583dd0f21f4e347cc233b0670a/src/adapt/vtree.js#L21
- https://github.com/vivliostyle/vivliostyle.js/blob/c30d5972cf0ae6583dd0f21f4e347cc233b0670a/src/adapt/vgen.js#L1100

An absolutely positioned element can be placed at a wrong position when its containing block is specified by a `position: relative` element, since the application of the `position` value is delayed and another wrong element may be chosen as its containing block. This sometimes leads to incorrect pagination where a page break occurs even if there remains room for subsequent contents.

`position: relative` should not affect layout of subsequent (sibling) elements, but _should_ affect pagination. In this sense, I think the delay should be dropped.

**Comment by kwkbtr** [comment]
> `position: relative` should not affect layout of subsequent (sibling) elements, but _should_ affect pagination.

This statement may be wrong, may be not.
[CSS Fragmentation 3 says](https://drafts.csswg.org/css-break/#transforms):

> Fragmentation interacts with layout, and thus occurs _before_ relative positioning [CSS21], transforms [CSS3-TRANSFORMS], and any other graphical effects. Such effects are applied per fragment ... However, the separation and transfer of page boxes _should_ occur last; thus a transformed fragment that spans pages _should_ be sliced at the page breaks and print in its entirety rather than being clipped by its originating page.

Both AHF and Prince seem to
- Paginate the content _before_ relative positioning,
- Apply relative positioning per fragment,
- Clip content outside each page area.

For example, if the element is shifted downward by a positive `top` value, part of the content that resulted being outside of the page area of the first page _is not_ rendered on the second page but is simply clipped. ([sample HTML](https://dl.dropboxusercontent.com/u/2680203/vivliostyle/js-issue-158/relative-positioning.html)) This behavior seems to violate the second sentence of the above quotation.

**Comment by frivoal** [comment]
Agreed, that behavior form AHF and Prince is a spec violation, and I agree with the spec. Do you think it should be changed?

As for the abspos bug, I think that position should be allowed to compute to relative before fragmentation, so that descendant abspos find the correct containing block, but its effect should be delayed until after fragmentation (equivalent to delaying top/left/bottom/right?).

**Comment by kwkbtr** [comment]
> Do you think it should be changed?

Maybe yes, but not confident. If we regard relative positioning as a purely decorative effect (not affecting layout), the overflowing part should be rendered on page margins and bleed area but not on the next page. This is similar to the case when some characters have decorative glyphs and the renderings overflow from the page area, the overflowing part should not be rendered on the next page.

For multi-columns, another fragmentation other than pagination, UAs behave differently from each other.
Test case: http://jsbin.com/wiziqikigi/edit?html,css,output
WebKit/Blink render the overflowing content on the next column, whereas Gecko/AHF/Prince do not send the part to the next column.

> As for the abspos bug, I think that position should be allowed to compute to relative before fragmentation, so that descendant abspos find the correct containing block, but its effect should be delayed until after fragmentation (equivalent to delaying top/left/bottom/right?).

Agreed. Delaying top/left/bottom/right may be a good idea. I will look into if it works.

**Comment by kwkbtr** [comment]
The problem with `position: absolute` elements was fixed by #172.
Behavior of `position: relative` is now identical to that of AHF and Prince. If we further need to change the behavior, we will create a new issue to track that.
