### ISSUE TITLE
Support more general `an+b` arguments for :nth-child selector

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#163]
- Single integer arguments are supported by #69 and `even`/`odd` arguments are supported by #162.
- More general `an+b` arguments should be supported.
- Spec: [Selectors Level 3 - :nth-child() pseudo-class](http://www.w3.org/TR/css3-selectors/#nth-child-pseudo)

**Comment by frivoal** [comment]
What do you mean by `an+b-1` is that different from `an+b`?

**Comment by kwkbtr** [comment]
Oops, I misread the spec.
