### ISSUE TITLE
Unbreakable too long lines make entire contents get shrunk on print from Google Chrome

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#165]
When there are unbreakable (typically elements with `white-space: pre`) lines, too long to fit in pages, the entire contents get shrunk on print from Google Chrome.
Vivliostyle Formatter has the same problem.

**Comment by frivoal** [comment]
We should probably solve this by making the overflow property apply on @page. When printing, overflow:hidden is probably the reasonable thing to do, but on screen, overflow:auto makes sense as well.

When doing this though, we should consider how this interacts with the bleed area. I haven't given it too deep thoughts, but I guess overflow:visible should overflow from the page box into the bleed area, but other values should not.

And if you overflow the bleed area itself, we should probably always clip that.

**Comment by kwkbtr** [comment]
This has been fixed by #169.
Page contents are always clipped by the bleed area, which coincides with the page box when the `bleed` property computes to zero.

It probably makes sense to enable `overflow:auto` applied within @page rules on screen.
I'm going to close this issue, but we can continue discussion on another issue if we want.
