### ISSUE TITLE
Math inside a table contains unnecessary line breaks

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#167]
Original issue: mathjax/MathJax#1364

When width of a table column is not specified (hence the width depends on browser's automatic layout), math inside such a column sometimes contains unnecessary line breaks, even if there is an enough space on the page. The reason for this behavior is that the column width _before_ typesetting the math is narrower than width required for the typeset math to fit inside the column.

**Comment by kwkbtr** [comment]
Though the upstream bug (mathjax/MathJax#1364) was fixed, this still occurs in Vivliostyle.

**Comment by pkra** [comment]
Note that the bug was fixed but the release which includes it has not yet been wrapped up.

**Comment by kwkbtr** [comment]
@pkra Thanks! I mistakenly thought that the bug fix was included in v2.6.1.

**Comment by kwkbtr** [comment]
Resolved by updating MathJax to 2.7. (vivliostyle/vivliostyle-ui#42)
