### ISSUE TITLE
Which JS module format to use?

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#2]
How should we manage JS modules and build distribution files?

* Simply concatenate separate JS files
 * Pros: No additional code for module loading
 * Cons: Dependency management may get complicated with increased number of source files
* CommonJS + browserify
 * Pros: Automatic dependency resolution
 * Cons: The build process with browserify is required even in development
* AMD + RequireJS
 * Pros: Automatic dependency resolution, the build process is not required in development
 * Cons: Require a module loader (require.js)
   * It may be possible to bundle a small module loader to build standalone distribution files.  
     cf. [How can I provide a library to others that does not depend on RequireJS?](http://requirejs.org/docs/faq-optimization.html#wrap)

**Comment by kwkbtr** [comment]
Cons of CommonJS + browserify would be negligible with an appropriate "watch" feature of a task runner.

+1 for CommonJS + browserify.

**Comment by kwkbtr** [comment]
Maybe we can defer the decision until some amount of code is written.

**Comment by johanneswilm** [comment]
I generally tend to go with the solution that means the least amount of code dependency, especially when writing library code that one thinks others will use in different projects in the future. But I am not sure that's what the idea is with this vivliostyle.js. And I can see the advantages of the other two options as well.

**Comment by kwkbtr** [comment]
I suppose it is one of the goals of vivliostyle.js to be widely used in various web sites and software projects. I agree that it is important to keep code dependency minimum for usability as a library.

We can start with the simple JS files (first option), and reconsider the other two options when (internal) code dependency get complicated and hard to manage.

**Comment by johanneswilm** [comment]
I think that sounds like a good compromise.

**Comment by kwkbtr** [comment]
[Knockout](https://github.com/knockout/knockout) seems to be a good example of simple module management.
In the build process source JS files are concatenated and wrapped by [some code](https://github.com/knockout/knockout/blob/master/build/fragments/amd-pre.js) to adapt the library to any existing module loader.
I'm going to try to start writing code in the same way.

**Comment by johanneswilm** [comment]
True. This looks very simple and universally usable.
