### ISSUE TITLE
Float images in pages

### ISSUE THREAD

**Issue by bobbytung** [vivliostyle/vivliostyle.js#20]
[Here](https://www.dropbox.com/s/ave4rd4uq5pxerd/pic2.png) is a sample that a image positioned by float: right and width: 50%. 

I remember that Johannes Wilm is editing CSS Page Floats. So I'd like to know how will vivliostyle project going to support it?

**Comment by kwkbtr** [comment]
We are planning to add support for some basic features of CSS Page Floats to Beta release, which will be out around this August.
We will announce details when available.

FYI, [CSS Page Floats editor's draft](http://dev.w3.org/csswg/css-page-floats/) is actively being updated by Johannes.
Also note that there was [an interesting discussion on CSS Page Floats](http://logs.csswg.org/irc.w3.org/css/2015-05-20/#e556160) in CSSWG F2F in NYC last week.

**Comment by kwkbtr** [comment]
Added very basic Page Floats support in #72.

**Comment by kwkbtr** [comment]
Experimental implementation has landed on [2017.2 release](https://github.com/vivliostyle/vivliostyle.js/releases/tag/2017.2).
