### ISSUE TITLE
float causes incorrect text offset

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#226]
This does not always happen.

https://www.dropbox.com/s/zjs9f2dhvrwjd25/float-bugbug-2.html?dl=0

![float-bugbug-2](https://cloud.githubusercontent.com/assets/3324737/14734825/0accb1d4-08a8-11e6-9144-096435a5e089.png)

https://www.dropbox.com/s/ni6if9amfiec3r7/float-bugbug-3.html?dl=0

![float-bugbug-3](https://cloud.githubusercontent.com/assets/3324737/14734833/1ad427f6-08a8-11e6-81f4-d80a76f0b546.png)

(These sample results may be problem of  recent patch, but similar problem was seen from the original adaptive-layout)

**Comment by kwkbtr** [comment]
This has been fixed by #228.
