### ISSUE TITLE
CSS Paged Media counter(pages) is not implemented

### ISSUE THREAD

**Issue by tomcruise81** [vivliostyle/vivliostyle.js#256]
As per the bottom of the [Page-based counters](https://www.w3.org/TR/css3-page/#page-based-counters) section, there is supposed to be:

> a counter named ‘pages’ [_that_] is automatically created by the UA. Its value is always the total number of pages in the document. (In continuous media this is always 1.) The value of ‘pages’ cannot be manipulated: while ‘counter-reset’ and ‘counter-increment’ statements that set it are valid, they have no effect.

Is there any intention of implementing that part of the spec?

**Comment by kwkbtr** [comment]
Sorry for the late response.
We want to support it in future releases, but it is not determined when we implement it.
We will let you know when it becomes available.
