### ISSUE TITLE
support "Q" and "H" as unit

### ISSUE THREAD

**Issue by kmuto** [vivliostyle/vivliostyle.js#281]
In Japanese typesetting, unit "Q" (1Q=0.25mm) and "H" (1H=0.25mm) are used widely.
It would be helpful if vivliostyle supports these unit in CSS.

**Comment by kwkbtr** [comment]
Sorry for the late response.

"q" unit (units are case-insensitive in CSS), which is [included in CSS Values and Units Level 3](https://www.w3.org/TR/css-values/#absolute-lengths), is already supported.
(If something does not work, please tell us.)

As far as I know "H" unit is not in any CSS spec now and Vivliostyle does not support it either.
@MurakamiShinyu @frivoal Do you think there is any chance that "H" is added to CSS in future?

**Comment by frivoal** [comment]
Adding a unit is not difficult on paper, but even such a small feature means a fair bit of busy work (publication, testing, implementation by multiple UAs, implementation reports...), and I expect at least google to push back ("not relevant to the web", "use preprocesors", "use other units"...), so the CSSWG will almost certainly demand use cases and market demand to justify this. If this is provided in a convincing enough manner though, why not.

**Comment by MurakamiShinyu** [comment]
"H" is same as "Q" which is already defined as "q" unit in CSS Values and Units. I think "q" is sufficient for both "Q" and "H".

**Comment by kmuto** [comment]
Thanks, this is my fault. Unit "q" worked.

And I myself am OK to use "Q" for alternative "H".
