### ISSUE TITLE
Initial value of orphans and widows is 2

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#30]
Spec: [CSS Fragmentation - 3.3. Breaks Between Lines: orphans, widows](http://dev.w3.org/csswg/css-break/#widows-orphans)

**Comment by frivoal** [comment]
This is an easy fix, right? if so, it should probably be higher priority, as it makes quite a bit impact on the readability.

**Comment by kwkbtr** [comment]
Right, I think the fix itself will take only a few minutes.
I remember there are some tests of orphans and widows in the csswg test repo, so I will spend an hour or so to find them and check if the fix make them pass.

**Comment by kwkbtr** [comment]
Fixed by #122.
