### ISSUE TITLE
Use 'dir' attribute on the root element when determining page progression direction

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#31]
Spec:
- [CSS Paged Media - 3.3. Page Progression](http://dev.w3.org/csswg/css-page/#progression)
- [CSS Writing Modes - 2.1. Specifying Directionality: the direction property](http://dev.w3.org/csswg/css-writing-modes-3/#direction)

**Comment by MurakamiShinyu** [comment]
Implemented at #443 and available since https://github.com/vivliostyle/vivliostyle.js/releases/tag/2018.8.100
