### ISSUE TITLE
cdn.mathjax.org closing

### ISSUE THREAD

**Issue by pkra** [vivliostyle/vivliostyle.js#344]
FYI https://www.mathjax.org/cdn-shutting-down/. 

I can only see one test file in this repo referencing our cdn but perhaps there are more elsewhere.

**Comment by kwkbtr** [comment]
Thank you for letting us know!
(I have read the news before but haven't taken any action yet 😄)
Actually, our UI module [has a reference to the cdn.mathjax.org](https://github.com/vivliostyle/vivliostyle-ui/blob/d74d470b49f44b52e98b00cd149cbb8aa3ebe5e1/src/html/vivliostyle-viewer.ejs#L10), which needs to be updated to cdnjs.

**Comment by pkra** [comment]
Thanks, @kwkbtr!
