### ISSUE TITLE
Adding a page selector button

### ISSUE THREAD

**Issue by julientaq** [vivliostyle/vivliostyle.js#350]
For now, you need to pass all page one by one to get to a specific part of the book you’re rendering.

Is there any way to add a GO TO PAGE XX button?

Thanks.

**Comment by maxiplay** [comment]
It seems when you click on a chapter title in table of content, the page is changed.

Possible hack :

We can imagine a running header hidden on all the book. it will contain href and when you want go to a specific chapter you can "click" on href with javascript.

**Comment by MurakamiShinyu** [comment]
"Go to Page" is implemented since https://github.com/vivliostyle/vivliostyle.js/releases/tag/2018.10.100
