### ISSUE TITLE
Some list formatting types get ignored

### ISSUE THREAD

**Issue by tgr** [vivliostyle/vivliostyle.js#372]
While trying to render Wikipedia articles such as [Berlin](http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://en.wikipedia.org/api/rest_v1/page/html/Berlin/789016409/dafce1d2-60f8-11e7-94fe-c76bc93369a4), some lists are displayed with default styling instead of the styling specified by the page. [Test page](http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://en.wikipedia.org/api/rest_v1/page/html/Berlin/789016409/dafce1d2-60f8-11e7-94fe-c76bc93369a4) (using the vivliostyle.github.io installation with Chrome version 59.0.3071.86 (64-bit official build) on Ubuntu 16.04) - see the gallery in the [Capital city](https://en.wikipedia.org/api/rest_v1/page/html/Berlin/789016409/dafce1d2-60f8-11e7-94fe-c76bc93369a4#Capital_city) section, implemented as an `ul` with `li { display: inline-block; }`. Vivliostyle renders it as if it were `display: list-item` - each item on a separate row, with a dot to the left.

**Comment by kwkbtr** [comment]
Thank you for the report.
The cause of the problem is the same as #371.

**Comment by MurakamiShinyu** [comment]
Close. Same as:
- https://github.com/vivliostyle/vivliostyle.js/issues/371#issuecomment-1283462168
