### ISSUE TITLE
page note not working inside blockquote

### ISSUE THREAD

**Issue by mrchristian** [vivliostyle/vivliostyle.js#375]
Hi,

Using the new Vivliostyle 6.17 I have a problem that did not exist before.

Pagenotes will not render and prevent the in browser rendering from viewing any more pages beyond the fault point.

e.g. 
`<blockquote><p>born as a historically-placed response to the emergence of capitalism, where it made it possible to organise labor and reify life into a commodity. If this is a negative heritage we now reject, there are also aspects of the project that can be rethought as means of resistance: the idea that creating a future does not mean necessarily to impose a form, but rather to imagine a set of relationships that can change, shift, readjust.<span class="footnote">Ibid.</span></p></blockquote>`

Would be nice to be able to keep both my blockquote tags and span class footnote, as I want to use the HTML for standard web pages and outputting to EPUB via Transpect.

Many thanks

S

**Comment by MurakamiShinyu** [comment]
I could not reproduce the problem. I tested Vivliostyle Viewer with the HTML file containing the blockquote and stylesheet `.footnote { float: footnote; }`. It works as expected.

If you still have the problem, reopen this issue and attach a reproducible sample (HTML+CSS), please.
