### ISSUE TITLE
Automating test across multi browsers anticipating CI

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vivliostyle.js#412]
For more effective development, I agree that to integrate a cross-browser testing tool such that [BrowserStack](https://www.browserstack.com/). These tools help us while we adopt continuous integration.

Do you have any plans for the testing tool of Vivliostyle? I wonder how to check its outputs. (take and compare image/DOM snapshot?)

**Comment by MurakamiShinyu** [comment]
We have no specific plan yet and your idea is very welcome.
For now we are using Travis CI with SauceLabs. See: https://travis-ci.org/vivliostyle/vivliostyle.js

**Comment by spring-raining** [comment]
Sorry for the late reply, I understand the CI environment in this repository! If we'll integrate image snapshot testing, we may be able to use such that [pixelmatch](https://github.com/mapbox/pixelmatch), [blink-diff](https://github.com/yahoo/blink-diff) or [Resemble.js](https://github.com/HuddleEng/Resemble.js)
