### ISSUE TITLE
Support for running elements

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#424]
Spec: CSS Generated Content for Paged Media (GCPM) / §1.2 Running elements
- Working Draft: https://www.w3.org/TR/css-gcpm-3/#running-elements
- Editor's Draft: https://drafts.csswg.org/css-gcpm-3/#running-elements

**Comment by MurakamiShinyu** [comment]
_From @kwkbtr on January 21, 2016 7:43_

Running elements of CSS GCPM is not implemented yet, but we want to support it in near future.
Currently you can do similar (but not the same) things in a non-standard way using Adaptive Layout features. You can read a tutorial of Adaptive Layout here: http://sorotokin.com/adaptive-layout/

**Comment by MurakamiShinyu** [comment]
Spec:
- https://drafts.csswg.org/css-gcpm-3/#running-headers-and-footers
  - https://drafts.csswg.org/css-gcpm-3/#running-elements
- https://drafts.csswg.org/css-gcpm-4/#copy-into-heading (?)

**Comment by MurakamiShinyu** [comment]
Related issue: "Support named strings for running headers and footers" #545

**Note:** (from https://drafts.csswg.org/css-gcpm-3/#running-headers-and-footers)
> **Named strings** copy text for reuse in margin boxes. **Running elements** move elements (complete with style and structure) from the document to margin boxes.

**Comment by fblome** [comment]
I would love to see this feature! 😍

**Comment by MurakamiShinyu** [comment]
@fblome Hi, I'd like to support this feature in the not very distant future.

To make running headers, the [named strings](https://www.w3.org/TR/css-gcpm-3/#named-strings) feature is already available. Does this not suit your purpose?

It would be helpful if you could give specific examples of where the running element feature is needed.

**Comment by MurakamiShinyu** [comment]
Implemented in #1170.

See tests in:
- https://github.com/vivliostyle/vivliostyle.js/pull/1170#issuecomment-1544980701

**Comment by fblome** [comment]
> @fblome Hi, I'd like to support this feature in the not very distant future.
> 
> To make running headers, the [named strings](https://www.w3.org/TR/css-gcpm-3/#named-strings) feature is already available. Does this not suit your purpose?
> 
> It would be helpful if you could give specific examples of where the running element feature is needed.

Hello and sorry for the late reply; the git notification went straight to the spam folder.

I see in the meantime you completed to implement the CSS running elements. Do you still need examples?

**Comment by MurakamiShinyu** [comment]
@fblome Hi, please try vivliostyle's running elements support with your examples and feedback us if you find any problem.
