### ISSUE TITLE
Make DocumentOptions.url observable

### ISSUE THREAD

**Issue by mb21** [vivliostyle/vivliostyle.js#457]
I've been trying to see whether this can be useful to my little editor project, where I want to have a print preview of an HTML document.

For the record, this actually works with the right files in the `resources` and `samples` directories (feel free to copy this to the README):

```javascript
var v = require('vivliostyle')
var viewerSettings = {
   userAgentRootURL: '/resources/' //put the files from /resources there
 , viewportElement: document.getElementById("vivliostyle-viewer-viewport") //make sure you have such an element
 , debug: true
};

// see https://github.com/vivliostyle/vivliostyle.js/blob/master/src/vivliostyle/viewer.js
// and https://knockoutjs.com/documentation/observables.html

var viewerOptions = {
  "autoResize": true,
  "fontSize": 16,
  "pageBorderWidth": 1,
  "renderAllPages": true,
  "pageViewMode": "SINGLE_PAGE", //PageViewMode.AUTO_SPREAD,
  "zoom": 1,
  "fitToScreen": false,
  "defaultPaperSize": undefined
};
var viewer = new v.viewer.Viewer(viewerSettings, viewerOptions)

var blob = URL.createObjectURL(
  new Blob([`<!DOCTYPE html>\n<html><head><style></style></head><body><h1>hi</h1></body></html>`], {type : 'text/html'})
);
var documentOptions = {url: blob};
viewer.loadDocument(documentOptions)
```

But I've been wondering whether there is a way to make that blob observalbe. But e.g. the following errors out cryptically:

```javascript
var blob = ko.observable(URL.createObjectURL(
  new Blob([`<!DOCTYPE html>\n<html><head><style></style></head><body><h1>hi</h1></body></html>`], {type : 'text/html'})
));
viewer.loadDocument({url: blob})
```

Or is the only way to do this, to call `loadDocument` with a new `Blob` each time? That doesn't sound very performant... Any pointers appreciated!

**Comment by spring-raining** [comment]
Actually, `loadDocument()` is a much heavier task than creating the new blob object due to the layout method of Vivliostyle cannot cache the layout information. Placing element task is interdependent deeply so it's difficult to reuse the previous result.

I suggest you implement a deferred execution gimmick. I don't know much about `ko.observable`, but it becomes such like

```js
// We call this to update a print preview.
function render(html) {
  const blob = new Blob([html], {type: 'text/html'});
  viewer.loadDocument({url: blob});
}
// Invoking the render function will be delayed until after 5 seconds
// have been elapsed since the last change event called.
editor.on('change', _.debounce(render, 5000);
```

by using `debouce()` function of [lodash](https://github.com/lodash/lodash).

**Comment by mb21** [comment]
> Actually, `loadDocument()` is a much heavier task than creating the new blob object

Ah, that's good to know and makes somewhat sense.

> due to the layout method of Vivliostyle cannot cache the layout information.

I guess that cannot really be changed anymore...?

Thanks for your quick reply! Then this issue can be closed.

**Comment by spring-raining** [comment]
Of course it is the one of the important topics to accelerate rendering time. We're dedicated to improving Vivliostyle!

**Comment by mb21** [comment]
Have you thought about using CSS columns to do page fragmentation? The more you can use the browser's rendering engine, the less you would have to recalculate when the HTML is changed.
