### ISSUE TITLE
how to use in server to generate page html data ?

### ISSUE THREAD

**Issue by ghost** [vivliostyle/vivliostyle.js#461]
how to use in server to generate page html data ?

**Comment by spring-raining** [comment]
Hello naxiaoguang,

A PDF generation system of vivliostyle.js relies on a renderer of browsers and we cannot use it browser-independently. You may check **headless browsers** and its API to controll browser in server ([**puppeteer**](https://github.com/GoogleChrome/puppeteer) is well known library for manipulating headless chrome).

If you want to use it more easily, please check also [**viola-savepdf**](https://www.npmjs.com/package/viola-savepdf), which is a generating PDF tool by using vivliostyle.js and headless chrome.

**Comment by ghost** [comment]
> Hello naxiaoguang,
> 
> A PDF generation system of vivliostyle.js relies on a renderer of browsers and we cannot use it browser-independently. You may check **headless browsers** and its API to controll browser in server ([**puppeteer**](https://github.com/GoogleChrome/puppeteer) is well known library for manipulating headless chrome).
> 
> If you want to use it more easily, please check also [**viola-savepdf**](https://www.npmjs.com/package/viola-savepdf), which is a generating PDF tool by using vivliostyle.js and headless chrome.

thanks !
