### ISSUE TITLE
how to just convert html doc to html pages data ,no sample ?   

### ISSUE THREAD

**Issue by ghost** [vivliostyle/vivliostyle.js#462]
how to just convert html doc as an article to page list data ,then can send each page to server saved

**Comment by MurakamiShinyu** [comment]
I guess you want to convert single HTML file to multiple HTML files using Vivliostyle.js's pagination, correct? 

Vivliostyle.js itself has no such feature but can generate paginated view, as you can see samples on https://vivliostyle.org/samples/.

If you want to make such feature using vivliostyle.js, the following source code may help you:

* https://github.com/vivliostyle/vivliostyle-ui/
* https://github.com/vivliostyle/vivliostyle-print/
* https://github.com/violapub/viola-savepdf/
