### ISSUE TITLE
Can not CLA signed

### ISSUE THREAD

**Issue by kubosho** [vivliostyle/vivliostyle.js#509]
## Reproduce

1. Go to https://www.clahub.com/agreements/vivliostyle/vivliostyle.js
2. Submit `Sign in with GitHub to agree to this CLA`
3. Allow OAuth in GitHub
4. Show message of `We're sorry, but something went wrong.` in https://www.clahub.com/agreements/new

**Comment by spring-raining** [comment]
Thanks for your report, I've confirmed this issue too. Currently, it seems that there's no other way than to wait for the problem solved.

c.f. https://github.com/clahub/clahub/issues?utf8=%E2%9C%93&q=is%3Aissue+%22something+went+wrong%22

Sorry for the inconvenience!

**Comment by kubosho** [comment]
Succeeded CLA sign.

I tried to submit "Sign in with GitHub to get started »" in CLAHub top page.
And retry signed in https://www.clahub.com/agreements/vivliostyle/vivliostyle.js.
And then CLA sign succeeded.
