### ISSUE TITLE
Embedding vivliostyle.js

### ISSUE THREAD

**Issue by zopyx** [vivliostyle/vivliostyle.js#513]
Is it possible to embed vivliostyle.js into an arbitrary HTML element of a website?

The usecase is have something like `<div id="viewer" data></div>` in my website or my CMS and embed the viewer into this particular `div#viewer` or is the viewer only intended to be used only as standalone application?

**Comment by MurakamiShinyu** [comment]
You can embed [Vivliostyle Viewer](https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html) (vivliostyle.js + vivliostyle-ui) using `<iframe>`, e.g.:

```
<iframe src="https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://vivliostyle.github.io/vivliostyle.js/samples/gutenberg/Alice.html&amp;renderAllPages=true" frameborder="0" style="width: 100%; height: 600px"></iframe>
```

If you don't want to use this public online [Vivliostyle Viewer](https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html), you can copy the viewer in the [download package](https://vivliostyle.org/download/) to your website.

If you want to embed vivliostyle.js without [vivliostyle-ui](https://github.com/vivliostyle/vivliostyle-ui), it will be also possible (but not very easy). There are examples of using vivliostyle.js without vivliostyle-ui:

- https://github.com/vivliostyle/vivliostyle-print - introduced in https://vivliostyle.org/blog/2018/10/03/vivliostyle-print/
- https://github.com/violapub/viola-savepdf - introduced in https://vivliostyle.org/blog/2018/11/22/introduction-of-viola/
