### ISSUE TITLE
Pass the tests for TypeScript source

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vivliostyle.js#520]

**Comment by MurakamiShinyu** [comment]
## Steps to test TS-converted vivliostyle.js with vivliostyle-ui (Vivliostyle Viewer)

(Before start, make sure that [Node.js](https://nodejs.org/) and [Compass](http://compass-style.org/) are installed.)

Install, build and start the test server:

```sh
git clone -b TS https://github.com/vivliostyle/vivliostyle.js.git
git clone -b js-ts-test https://github.com/vivliostyle/vivliostyle-ui.git

cd vivliostyle.js
npm install
npm run build           # production build
npm run build-dev       # development build

cd ../vivliostyle-ui
npm install
npm link ../vivliostyle.js
npm run build           # production build
npm run serve-dev       # dev build and serve
```

Open http://localhost:3000/vivliostyle.js/test/files/ and check the test casses' **dev** and **prod** links for each build.

Press `Ctrl-C` to stop the test server.

**Comment by MurakamiShinyu** [comment]
Currently, all above tests seems passed.

**Comment by MurakamiShinyu** [comment]
For automated vivliostyle.js test, current [Karma configuration](https://github.com/vivliostyle/vivliostyle.js/blob/8c3c7da67aacc0073d3c036d9130c8bfd02b267e/test/conf/karma-common.conf.js) is dependent with old JS source and not yet updated for TS source. We will treat it as another issue.
