### ISSUE TITLE
ASCIIMATH and MathJAX

### ISSUE THREAD

**Issue by NoBodyButMe** [vivliostyle/vivliostyle.js#523]
Hello

I want to use vivliostyle and MathJax to render ASCIIMATH, but that doesn't seem to be possible.

When I use the following code in another page it works without any problem:

<script>
    MathJax.Hub.Config({
      asciimath2jax: {
        delimiters: [['`','`'], ['$','$']]
      }
    });
</script>
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
    

But when I try to use it in the "viewer" it only renders MathML, but not the ASCIIMATH-code.

**Comment by NoBodyButMe** [comment]
It seems vivlio kan only render MathML? Is that correct? Can I use Latex of ASCIIMATH in any way?

**Comment by MurakamiShinyu** [comment]
I admit the problem that the documentation about TeX/AsciiMath support is missing except in the [Change Log](https://github.com/vivliostyle/vivliostyle/blob/master/CHANGELOG.md#20164---2016-04-08):

- Support TeX and AsciiMath mathematics
  - <https://github.com/vivliostyle/vivliostyle/issues/108>
  - In a element with `data-math-typeset="true"` attribute, you can use TeX or AsciiMath mathematics.
  - TeX mathematics are indicated by delimiters `\(...\)` or `$$...$$`.
  - AsciiMath mathematics are indicated by delimiters `` `...` ``.

See also the test file
https://github.com/vivliostyle/vivliostyle/blob/master/packages/core/test/files/math-sample.html

and Vivliostyle output: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://github.com/vivliostyle/vivliostyle/blob/master/packages/core/test/files/math-sample.html

**Comment by NoBodyButMe** [comment]
Thanks, it helps a lot :-)
