### ISSUE TITLE
Vexflow and vextab

### ISSUE THREAD

**Issue by NoBodyButMe** [vivliostyle/vivliostyle.js#524]
Does vivlio support Vexflow/vextab for music engraving?

**Comment by MurakamiShinyu** [comment]
No, unfortunately. I added "feature request " label.

**Comment by MurakamiShinyu** [comment]
Vivliostyle.js [v2.13.0](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.13.0) has been released, with the new feature:
> - Allow JavaScript in HTML documents ([ccd31da](https://github.com/vivliostyle/vivliostyle.js/commit/ccd31da5ff3eba91432953580483548cecd84859)), closes [#733](https://github.com/vivliostyle/vivliostyle.js/issues/733) [#735](https://github.com/vivliostyle/vivliostyle.js/issues/735)

Now you can use Vivliostyle with Vexflow/vextab for music engraving.

test: https://github.com/vivliostyle/vivliostyle.js/issues/733#issuecomment-1007294094

> Test VexTab Tutorial (http://vexflow.com/vextab/tutorial.html)
> 
> * https://vivliostyle.vercel.app/#src=https://raw.githack.com/0xfe/vextab/master/doc/tutorial.html
