### ISSUE TITLE
Firefox only prints 1st page in Vivliostyle 2019.1.103 and higher

### ISSUE THREAD

**Issue by ayhy** [vivliostyle/vivliostyle.js#525]
Tested on: Firefox 67.0.1, Vivliostyle 2019 1.103, 2019 1.104 and 2019.1.105

Additional note:
It is more likely due to Firefox bug, as [Firefox has reportedly has issue in printing multi pages with flex elements](https://bugzilla.mozilla.org/show_bug.cgi?id=939897) and older Vivliostyle was unable to print page counter (which had flex element), which presumably comes from the same root. It seems changes made between 2019 1.102 and 2019 1.103 added some element that glitches Firefox.

My current workaround is to use ver. 2019 1.102 and add page number by other PDF editor. If there's any other workarounds that I can use newer version of Vivliostyle, I'd like to know.

**Comment by MurakamiShinyu** [comment]
Thanks for reporting the issue.
I found this problem is a side effect of https://github.com/vivliostyle/vivliostyle.js/pull/514 - (re)workaround for Chrome printing problem.

**Comment by MurakamiShinyu** [comment]
I made a workaround for this problem: https://github.com/vivliostyle/vivliostyle.js/commit/05b61daf9653ef3648bc7455d7dfa3aef085f31c

@ayhy Please try the Latest Development Version (2019.1.106-pre) that includes this.

**Comment by ayhy** [comment]
Thank you.
