### ISSUE TITLE
no CSS crashes browser

### ISSUE THREAD

**Issue by johanneswilm** [vivliostyle/vivliostyle.js#526]
If one runs vivliostyle.js on a page without any CSS, then it crashes both Firefox and Chrome.

How to reproduce:

1. Go to https://vivliostyle.github.io/vivliostyle-print/ .

2. Click into the CSS editor.

3. On your keyboard hit CTRL+A to select everything.

4. Delete the text by hitting "Backspace".

5. Click on the "print" button.

 
Notice: This bug could also be in vivliostyle-print, as it's a bit hard to test vivliostyle.js directly. But after looking through the vivliostyle-print source code I cannot find any place where this could come in.

**Comment by MurakamiShinyu** [comment]
Deleting `@page { size: A4; ...}` causes the problem on the vivliostyle-print demo.

This seems because the initial value of the `size` property is **auto** and the vivliostyle.js uses window size for **auto** page size, and in this vivliostyle-print case, hidden `<iframe>` is used and its window size is zero.

**Comment by johanneswilm** [comment]
@MurakamiShinyu Thank you. I have now set a non-zero default page size in `vivliostyle-print`. However - I would think that it would be good if we could as much as possible make vivliostyle.js not crash the browser, even if it gets insane CSS to deal with. If it would just throw an error and stop processing if it finds out it is is producing an insane amount of pages would be a good option to have.

**Comment by johanneswilm** [comment]
#460 covers the remaining feature I would like to have.
