### ISSUE TITLE
Increase printWidth for Prettier config

### ISSUE THREAD

**Issue by kubosho** [vivliostyle/vivliostyle.js#550]
> kubosho_ 02:51
> あと行数についても書いておくと、最近のパソコンは Full HD もしくはそれ以上の解像度を持ったディスプレイを搭載していることが多いので、そういった環境でソースコードを見やすくしたつもりです。
> As for the number of lines, I would like to make it easier to see the source code in such an environment, since modern computers often have a display with Full HD or higher resolution.

quote from: https://vivliostyle.slack.com/archives/CAECW4S93/p1568742682013300

> shinyu 02:53
> 了解です。vivliostyle-ui はこれで良いと思います。vivliostyle.js のほうもprintWidthは大きくした方がよいかもしれないですね。
> I understand. I think this is good for vivliostyle-ui. vivliostyle.js may also have a larger printWidth.

quote from: https://vivliostyle.slack.com/archives/CAECW4S93/p1568742837014900

**Comment by MurakamiShinyu** [comment]
We decided to not change from the Prettier default, as I wrote in our slack https://vivliostyle.slack.com/archives/CNN5GPF9V/p1570589074067100.
