### ISSUE TITLE
Emulate 'font-variant: tabular-nums' with 'font-feature-settings: "tnum" on' 

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle.js#581]
In browsers that do not support `font-variant: tabular-nums` (`if(! CSS.supports('font-variant', 'tabular-nums')) { /*...*/ }`), emulate it using `font-feature-settings: "tnum" on`

**Comment by MurakamiShinyu** [comment]
Currently all major browsers support  `font-variant: tabular-nums` (I confirmed that `CSS.supports('font-variant', 'tabular-nums'` returns true), so such emulation would be no longer necessary.
