### ISSUE TITLE
Support 'font-stretch' descriptor in @font-face rule

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#610]
`font-stretch` descriptor in an `@font-face` rule does not cause an error, but is simply ignored.
It should be properly handled to be used for font matching.

Related to vivliostyle/vivliostyle#36.

**Comment by MurakamiShinyu** [comment]
Duplicate of #591

> Resolved by 504896bc9a388c22a7f02ac4704778063472f741
> 
> > * Add support for the font-stretch descriptor in the `@font-face` rule
