### ISSUE TITLE
[viewer] Deciphered URL parameters

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vivliostyle.js#628]
**Describe the bug**
We should stop single character URL parameters like `#x` and `#b`.

**Expected behavior**
- `#b` → `#src=<url>&renderAllPages=false&bookMode=true`
- `#x` → `#src=<url>&renderAllPages=true&bookMode=false`

**Discussion**

- Name suggestion for `renderAllPages`
- Default value for `renderAllPages`, `bookMode`

**Comment by MurakamiShinyu** [comment]
Default: `renderAllPages=true`, `bookMode=false`
