### ISSUE TITLE
Deprecate vivliostyle package in npm

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vivliostyle.js#636]
`npm deprecate vivliostyle` and point at `@vivliostyle/core`.

# Tooling

- https://www.npmjs.com/package/@tiaanduplessis/pkg-rename

**Comment by MurakamiShinyu** [comment]
This seems to have already been done.

![Screen Shot 2021-03-22 at 15 31 43](https://user-images.githubusercontent.com/3324737/111949412-0e4ddf00-8b24-11eb-9efe-a6541e9f06c7.png)
