### ISSUE TITLE
Error handling on invalid XML (EPUB)

### ISSUE THREAD

**Issue by hrvoj3e** [vivliostyle/vivliostyle.js#638]
## Problem
Download epub from http://elektronickeknjige.com/download/etika-kruha-i-konja/epub/
Unpack it with `unzip`
```
unzip etika-kruha-i-konja.epub -d pub/pack2/etika-kruha-i-konja
```

```
curl -IL '<my-server>pub/pack2/etika-kruha-i-konja/OEBPS/book.opf'
HTTP/2 200 
server: nginx/1.18.0
date: Tue, 02 Jun 2020 09:43:33 GMT
content-type: application/oebps-package+xml
content-length: 10941
last-modified: Mon, 16 Mar 2020 11:09:42 GMT
etag: "5e6f5e76-2abd"
accept-ranges: bytes
```

Try to load it as 
`https://vivliostyle.org/viewer/#src=<my-server>/epub/pack2/etika-kruha-i-konja/OEBPS/book.opf`
but getting 
> Received an empty response for my-server/epub/pack2/etika-kruha-i-konja/OEBPS/book.opf. This may be caused by the server not allowing cross-origin resource sharing (CORS).

## Expected
Load epub or output clear message error.
It is not CORS - tried running on the same domain - same result.

## Using
https://github.com/vivliostyle/vivliostyle.js/releases/download/v2.0.0/vivliostyle-viewer-2.0.0.zip
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

**Comment by hrvoj3e** [comment]
Found it - XML file `OEBPS/book.opf` is not valid.

Could you maybe output a more specific error in this case? 
Response is not empty and it is not related to CORS. 

Also, is there a plan to allow loading od epub files directly (client side unpack)?
For now epub must be unpacked.

**Comment by MurakamiShinyu** [comment]
This problem is not a bug but the error handling in the vivliostyle.js/core is not very good.

around this line:
https://github.com/vivliostyle/vivliostyle.js/blob/88425881b896aef9ef0fbfdd1cd7d0d553e8fda6/packages/core/src/vivliostyle/epub.ts#L373
