### ISSUE TITLE
Is IE11 out of support?

### ISSUE THREAD

**Issue by JUNJUNJUN** [vivliostyle/vivliostyle.js#669]
**Describe the bug**
I can not open the document in IE11.

**To Reproduce**
1. Go to 'https://vivliostyle.org/viewer/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gon/index.html'
2. See error

**Expected behavior**
Is IE11 out of support?

**Screenshots**
![image](https://user-images.githubusercontent.com/4621358/99798894-5d7b0780-2b64-11eb-8bb2-d2dc9d655445.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 11

**Comment by MurakamiShinyu** [comment]
@JUNJUNJUN 
Hi, thanks for the report. Yes, IE11 is out of support, since 2018-09, see the change log:
https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#20188100---2018-09-10
> -   Test platform change: IE11 to Microsoft Edge
>     -   <https://github.com/vivliostyle/vivliostyle.js/commit/5c71209a>
>     -   IE11 is no longer supported
