### ISSUE TITLE
bug(react): startPage on loadDocument()

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#685]
**Describe the bug**

vivliostyle/react の Storybook でPageを1以外にしてSourceを変えたとき、そのSourceで指定される文書の先頭ページのページ番号がPageで指定された番号になる。
おそらく期待される動作は、新しい文書が表示されたときは先頭ページが表示されてPageが1にリセットされることだろう。
（Pageをリセットしないのであれば、先頭ページを表示するのではなく、先頭ページを1として、Pageで指定されたページを表示するべきだろう）

**To Reproduce**

1. packages/react ディレクトリで、 `yarn storybook` を実行
    →Storybook で「ごん狐」の最初のページ（ページ番号 1）が表示される
2. Knobs の Page が 1 になっているのを2に変える
    →「ごん狐」の2ページ目（ページ番号 2）が表示される
3. Knobs の Source を `https://vivliostyle.github.io/vivliostyle_doc/samples/gutenberg/Alice.html` に変える
    →「Alice」の最初のページが表示されるが、そのページ番号が「2」になっている

**Expected behavior**

この「Page」入力ボックスは、文書の何ページ目を表示するかを指定するものであって、文書の先頭ページのページ番号を指定するものではない。

ある文書のNページ目を表示してから別の文書の表示に切り替えたとき、同じNページ目を表示することが役に立つのか疑問だが、表示するPageを指定してから文書を開くという意味はあるかもしれない。その場合の期待される動作は、（Pageを2に変えてからSourceを「Alice」に変えたとき）「Alice」の2ページ目（ページ番号 2）が表示されるというものになる。

表示する文書を切り替えたときは常に先頭ページから表示するのであれば、先頭ページを表示して、「Page」入力ボックスが1にリセットされるようにするべきだろう。

**Screenshots**

![Screen Shot of the Storybook](https://user-images.githubusercontent.com/3324737/104844179-f71b2700-5911-11eb-81fe-9c87085d8d06.png)

**バグ原因: CoreViewer.loadDocument() への startPage の指定が誤りではないか**

https://github.com/vivliostyle/vivliostyle.js/blob/aeddc7fe365309ee136c2ab6d381126ddd695a54/packages/react/src/renderer.tsx#L130

この `instance.loadDocument({ url: source, startPage: page }, documentOptions, {…});` の startPage の指定に問題がありそうである。この startPage オプションについて、packages/core/src/vivliostyle/core-viewer.ts 内に次のようにコメントがある:

https://github.com/vivliostyle/vivliostyle.js/blob/aeddc7fe365309ee136c2ab6d381126ddd695a54/packages/core/src/vivliostyle/core-viewer.ts#L135-L152

> startPage: If specified, the `page` page-based counter is set to the specified value on the first page of the document.

（startPage オプションが 指定された場合、文書の先頭でpageカウンタが指定された値にセットされる）

この startPage オプションは、複数文書を連結してひとつの本にするときに、その中の個別の文書の開始ページ番号を指定する機能であり、通常の文書の表示では指定するべきではない。（参考: この機能はPR https://github.com/vivliostyle/vivliostyle.js/pull/258 で追加された）
したがってここは `, startPage: page` を削除して、次のように修正するとよいだろう:

```ts
      instance.loadDocument({ url: source }, documentOptions, {
```

しかしこれだけでは、文書を切り替えたとき先頭ページ（ページ番号 1）が表示されるが「Page」入力ボックスには文書を切り替える前に入っていた値が入ったままという問題がある。さらなる見直しが必要です。

**Comment by yukukotani** [comment]
@MurakamiShinyu ページ番号のバグについては、おっしゃる通りの原因だったので #686 で修正しました。

> しかしこれだけでは、文書を切り替えたとき先頭ページ（ページ番号 1）が表示されるが「Page」入力ボックスには文書を切り替える前に入っていた値が入ったままという問題がある。さらなる見直しが必要です。

これについては #687 に別途起票しました。先頭ページ以外から描画(組版)を始めることはできないので、ちゃんと対応するにはコア部分を大きく変更する必要がありそうです。
