### ISSUE TITLE
Missing source map

### ISSUE THREAD

**Issue by johanneswilm** [vivliostyle/vivliostyle.js#695]
Hey, when building vivliostyle-print, it is complaining about this file missing: `node_modules/@vivliostyle/core/lib/vivliostyle.js.map`. And indeed, it looks as if this file is not in the distribution even though it is referenced in `node_modules/@vivliostyle/core/lib/vivliostyle.js`.

**Comment by MurakamiShinyu** [comment]
I found that this problem existed since [v2.1.1](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.1.1):

> ## [2.1.1](https://github.com/vivliostyle/vivliostyle.js/compare/v2.1.0...v2.1.1) (2020-06-30)
> ### Bug Fixes
> - only generate commonjs ([08f6410](https://github.com/vivliostyle/vivliostyle.js/commit/08f64109a9a7ef485b0b8d783f2c0f3f969a1151))

In this commit, 

```json
  "files": [
    "lib",
```
was replaced with
```json
  "files": [
    "lib/**/*.js",
    "lib/**/*.d.ts",
```
