### ISSUE TITLE
Question: react renderer size

### ISSUE THREAD

**Issue by axelilali** [vivliostyle/vivliostyle.js#709]
**Describe the bug**
The react renderer seems to have a bigger size than the viewport and cannot be resized causing the browser to have scrollbars on the right side and the bottom of the browser.

**To Reproduce**
Cannot find a solution

**Expected behavior**
The content should fit the browser size

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs, Windows 10
 - Browser : Chrome, Safari, Edge
 - Version : latest

![Screenshot 2021-03-17 at 12 11 48](https://user-images.githubusercontent.com/9570320/111458708-0b18b480-871a-11eb-900b-d1a669a4bc7c.png)

**Comment by MurakamiShinyu** [comment]
@axelilali 
Thanks for your bug report!
Could you share your code that can reproduce the problem?

**Comment by axelilali** [comment]
Hi @MurakamiShinyu 
I basically created a simple react app using the same code as your component example and the same problem occurs.
`import React from "react";




import { Renderer } from "@vivliostyle/react";

function App() {
  const [page, setPage] = React.useState(1);

  function next() {
    setPage((page) => page + 1);
  }

  function prev() {
    setPage((page) => page - 1);
  }

  function onLoad(state) {
    console.log(state.epageCount, state.docTitle);
  }

  const sample =
    "http://vivliostyle.github.io/vivliostyle_doc/samples/gutenberg/Alice.html";

  return (
    <div className="box">
      <Renderer source={sample} page={page} onLoad={onLoad} fitToScreen={true} pageViewMode={'SPREAD'}/>
     
      
    </div>
  );
}

export default App;`

**Comment by MurakamiShinyu** [comment]
Hi @axelilali 

The example code generates the following DOM structure:

```html
<div id="root">
  <div>
    <div data-vivliostyle-viewer-viewport="true" ...>
      ... <!-- here, Vivliostye generates pages -->  ...
    </div>
    <button>Next</button>
    <button>Prev</button>
  </div>
</div>
```

Vivliostyle core engine generates pages in the vivliostyle-viewer-viewport (`<div data-vivliostyle-viewer-viewport="true">` element). If the size of the vivliostyle-viewer-viewport is not set, the entire window size is used. So other elements (buttons in this example) overflow and scroll bars appear.

You can set stylesheet to get the layout you want. For example,
add `import "./App.css"` to your `App.jsx` file, and create the stylesheet `App.css` file as follows:

```css
#root > div > div[data-vivliostyle-viewer-viewport] {
  width: 100vw;
  height: calc(100vh - 32px);
}
```

**Comment by MurakamiShinyu** [comment]
Changed the label and the issue title, because this is not a bug.

**Comment by axelilali** [comment]
Hi @MurakamiShinyu 
Thanks for your reply.

With this solution the zoom doesn't work. Any alternative for this ?
