### ISSUE TITLE
An element vanishes in a multicolumn layout

### ISSUE THREAD

**Issue by scivola** [vivliostyle/vivliostyle.js#741]
**Describe the bug**
An element vanishes in a multicolumn layout. The element is set as `break-inside: avoid`.

**Reproduction HTML**

```html
<!DOCTYPE html>
<meta charset="utf-8">
<style>
* {
  padding: 0;
  margin: 0;
}
@page {
  size: A4;
  padding: 0;
  margin: 0;
}
body {
  margin: 20mm;
  font-size: 10mm;
}
main {
  background: yellow;
  column-count: 2i;
  column-gap: 20mm;
  column-rule: 1mm dashed red;
}
.block {
  break-inside: avoid;
  height: 50mm;
  margin: 0 0 20mm;
  border: 1mm solid gray;
  box-sizing: border-box;
}
</style>
<main>
  <div class="block">1</div>
  <div class="block">2</div>
  <div class="block">3</div>
  <div class="block">4</div>
  <div class="block">5</div>
  <div class="block">6</div>
  <div class="block">7</div>
  <div class="block">8</div>
  <div class="block">9</div>
  <div class="block">10</div>
  <div class="block">11</div>
  <div class="block">12</div>
</main>
```

**Screenshots**
![mc-p1](https://user-images.githubusercontent.com/294125/125009667-eddc6d00-e09f-11eb-8021-cc997616d413.png)
![mc-p2](https://user-images.githubusercontent.com/294125/125009670-ef0d9a00-e09f-11eb-9a92-33e69013c433.png)

The 9th `.block` element vanished.

In addition, the bottom margin of the first page and the top margin of the second page have eliminated.

**Environment**
 - OS: macOS Catalina
 - Vivliostyle: cli 3.5.0, core 2.8.0

**Comment by MurakamiShinyu** [comment]
There is a known issue that Vivliostyle.js cannot handle correctly multi-column specified on elements other than the root or the body.

Related issue: https://github.com/vivliostyle/vivliostyle.js/issues/579

> > * **問題**：ルートあるいは body 以外の要素に指定した段組が正常に組版できない。
> > * **メモ**：現在の段組の実装は、EPUB Adaptive Layout でのページ区画で指定する段組の実装がベースで、ルートまたは body 要素に指定された段組をページエリア全体の段組の扱いに変えてサポートしている。それ以外の要素での段組のプロパティはそのままブラウザに渡されるので、ページの中で部分的に使われたときに機能するが、複数ページに渡るときの分割処理などはできていない。
> 
> (from https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol2/shinyu/index.html)


Workaround:
- move multi-column properties to the root or body element
- move the margin property for the multi-column box to the `@page`

e.g.,

```html
<style>
* {
  padding: 0;
  margin: 0;
}
@page {
  size: A4;
  margin: 20mm;
}
body {
  font-size: 10mm;
  background: yellow;
  column-count: 2;
  column-gap: 20mm;
  column-rule: 1mm dashed red;
}
.block {
  break-inside: avoid;
  height: 50mm;
  margin: 0 0 20mm;
  border: 1mm solid gray;
  box-sizing: border-box;
}
</style>
<body>
  <div class="block">1</div>
  <div class="block">2</div>
  <div class="block">3</div>
  <div class="block">4</div>
  <div class="block">5</div>
  <div class="block">6</div>
  <div class="block">7</div>
  <div class="block">8</div>
  <div class="block">9</div>
  <div class="block">10</div>
  <div class="block">11</div>
  <div class="block">12</div>
</body>
```

Test: https://vivliostyle.org/viewer/#src=https://jsbin.com/muyuqat

**Comment by scivola** [comment]
Thank you for your advice.
