### ISSUE TITLE
JIS B paper size

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#75]
In Japan, JIS B paper size is used much more often than ISO B paper size.
Should it be included to [CSS Paged Media Module](https://drafts.csswg.org/css-page/)?
We can implement a vendor extension to the `size` value, but having it in the spec is better.

**Comment by kwkbtr** [comment]
Ghostscript has `jisb0` to `jisb6` paper sizes defined: http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=Resource/Init/gs_statd.ps;hb=6948650efd3fb9e2a70b8cf16aca57e9d0b7eb0a#l91

**Comment by frivoal** [comment]
JIS-B4 and JIS-B5 have been added to CSS Paged Media Module:
https://drafts.csswg.org/css-page/#page-size-prop

We should update our implementation to match.

**Comment by kwkbtr** [comment]
Excellent!

**Comment by kwkbtr** [comment]
Done.
