### ISSUE TITLE
Too large line height when ruby exists in the line and line-height is less than 2.0 (Chrome)

### ISSUE THREAD

**Issue by butameron** [vivliostyle/vivliostyle.js#806]
**Describe the bug**
line-height: 2.0未満の時、Chromeで表示した際にルビがある行の行間だけが広くなる。

Firefoxでもline-height: 1.5未満にするとルビがある行の行間が広くなるが、line-height: 1.5以上にすると解消する。しかし、Chromeではルビ自体の幅が広いためか、line-height: 2.0以上にする必要がある。

例えば、組版の際、四六判に縦書き17～18行ほど詰め込もうとすると、line-height: 2.0では厳しいため、line-hight: 1.6～7程度まで行間を詰める必要があるが、CSSではルビのサイズを調整しづらいため実現が難しい。

**To Reproduce**
以下のHTMLをVivliostyleで表示する。（分かりやすいようにline-height: 1.0にしている）

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <style>
        @page {
            size: A5;
        }
        html {
            font-family: "源ノ明朝";
        }
        body {
            writing-mode: vertical-rl;
            line-height: 1.0;
        }
    </style>
</head>
<body>
    <ruby><rb>吾輩</rb><rp>（</rp><rt>わがはい</rt><rp>）</rp></ruby>は猫である。名前はまだ無い。<br />
    　どこで生れたかとんと<ruby><rb>見当</rb><rp>（</rp><rt>けんとう</rt><rp>）</rp></ruby>がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかもあとで聞くとそれは書生という人間中で一番<ruby><rb>獰悪</rb><rp>（</rp><rt>どうあく</rt><rp>）</rp></ruby>な種族であったそうだ。この書生というのは時々我々を<ruby><rb>捕</rb><rp>（</rp><rt>つかま</rt><rp>）</rp></ruby>えて<ruby><rb>煮</rb><rp>（</rp><rt>に</rt><rp>）</rp></ruby>て食うという話である。しかしその当時は何という考もなかったから別段恐しいとも思わなかった。ただ彼の<ruby><rb>掌</rb><rp>（</rp><rt>てのひら</rt><rp>）</rp></ruby>に載せられてスーと持ち上げられた時何だかフワフワした感じがあったばかりである。掌の上で少し落ちついて書生の顔を見たのがいわゆる人間というものの<ruby><rb>見始</rb><rp>（</rp><rt>みはじめ</rt><rp>）</rp></ruby>であろう。この時妙なものだと思った感じが今でも残っている。第一毛をもって装飾されべきはずの顔がつるつるしてまるで<ruby><rb>薬缶</rb><rp>（</rp><rt>やかん</rt><rp>）</rp></ruby>だ。その<ruby><rb>後</rb><rp>（</rp><rt>ご</rt><rp>）</rp></ruby>猫にもだいぶ<ruby><rb>逢</rb><rp>（</rp><rt>あ</rt><rp>）</rp></ruby>ったがこんな<ruby><rb>片輪</rb><rp>（</rp><rt>かたわ</rt><rp>）</rp></ruby>には一度も<ruby><rb>出会</rb><rp>（</rp><rt>でく</rt><rp>）</rp></ruby>わした事がない。のみならず顔の真中があまりに突起している。そうしてその穴の中から時々ぷうぷうと<ruby><rb>煙</rb><rp>（</rp><rt>けむり</rt><rp>）</rp></ruby>を吹く。どうも<ruby><rb>咽</rb><rp>（</rp><rt>む</rt><rp>）</rp></ruby>せぽくて実に弱った。これが人間の飲む<ruby><rb>煙草</rb><rp>（</rp><rt>たばこ</rt><rp>）</rp></ruby>というものである事はようやくこの頃知った。<br />
    　この書生の掌の<ruby><rb>裏</rb><rp>（</rp><rt>うち</rt><rp>）</rp></ruby>でしばらくはよい心持に坐っておったが、しばらくすると非常な速力で運転し始めた。書生が動くのか自分だけが動くのか分らないが<ruby><rb>無暗</rb><rp>（</rp><rt>むやみ</rt><rp>）</rp></ruby>に眼が廻る。胸が悪くなる。<ruby><rb>到底</rb><rp>（</rp><rt>とうてい</rt><rp>）</rp></ruby>助からないと思っていると、どさりと音がして眼から火が出た。それまでは記憶しているがあとは何の事やらいくら考え出そうとしても分らない。<br />
    　ふと気が付いて見ると書生はいない。たくさんおった兄弟が一<ruby><rb>疋</rb><rp>（</rp><rt>ぴき</rt><rp>）</rp></ruby>も見えぬ。<ruby><rb>肝心</rb><rp>（</rp><rt>かんじん</rt><rp>）</rp></ruby>の母親さえ姿を隠してしまった。その上<ruby><rb>今</rb><rp>（</rp><rt>いま</rt><rp>）</rp></ruby>までの所とは違って<ruby><rb>無暗</rb><rp>（</rp><rt>むやみ</rt><rp>）</rp></ruby>に明るい。眼を明いていられぬくらいだ。はてな何でも<ruby><rb>容子</rb><rp>（</rp><rt>ようす</rt><rp>）</rp></ruby>がおかしいと、のそのそ<ruby><rb>這</rb><rp>（</rp><rt>は</rt><rp>）</rp></ruby>い出して見ると非常に痛い。吾輩は<ruby><rb>藁</rb><rp>（</rp><rt>わら</rt><rp>）</rp></ruby>の上から急に笹原の中へ棄てられたのである。<br />
</body>
</html>
```

**Expected behavior**
Firefoxの場合、広がるとしてもルビの文字の幅＋α程度まで。
![image](https://user-images.githubusercontent.com/19877154/139230428-b4c806ba-50a3-448e-80a9-c5b71d5fa7dd.png)

**Screenshots**
Chromeの場合は行間が広がりすぎる。ルビの文字の幅だけでなく、隙間がある。
![image](https://user-images.githubusercontent.com/19877154/139230492-132c0864-b9de-4df5-8958-154fffdc3627.png)

参考：ChromeでVivliostyleを使用しない場合
![image](https://user-images.githubusercontent.com/19877154/139233622-9fe77b6c-cdad-4b82-a061-5f15e0b5fbc4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  94.0.4606.81（Official Build） （64 ビット）

**Additional context**
使用しているフォントは、SourceHanSerif.ttc 
https://github.com/adobe-fonts/source-han-serif/releases/tag/1.001R

Chromeの最小フォントサイズは0に設定している。
![image](https://user-images.githubusercontent.com/19877154/139235393-696a9ba6-6ebe-486b-8496-b3434bc180f3.png)

**Comment by MurakamiShinyu** [comment]
まず、ChromeでのVivliostyleでの表示と

> 参考：ChromeでVivliostyleを使用しない場合

との違いについて。

ChromeでVivliostyleを使用しない場合でも、Chromeで印刷/PDF保存をするとVivliostyleでの表示と同様の結果（ルビと親文字とが異常に離れる）になります。
テストしてみました：
![Screen Shot 2021-10-28 at 23 02 42](https://user-images.githubusercontent.com/3324737/139280388-eef04ece-af21-4177-98b3-c97a708e1624.png)

Chromeの画面表示と印刷/PDF保存で組版結果が違うという問題は、Vivliostyleの組版不具合(#758, #793)の原因になっていたので、最近その対策の修正をしました:

- https://github.com/vivliostyle/vivliostyle.js/pull/795

この修正によりVivliostyle Viewerでの表示がChromeでの印刷結果と同じになりました。（その結果、印刷だけでなくVivliostyle Viewerの表示でもルビと親文字が離れるようになった）

このpull reqで説明しているとおり、Chromiumは数年前から古いレイアウトエンジンを新しいレイアウトエンジンに切り替えつつあるのですが、新しいレイアウトエンジンのほうはまだ印刷と段組みに対応していない（ページ/段の分割処理ができていない）ために、印刷と段組みには古いレイアウトエンジンが使われています。

Vivliostyleの組版処理では、ブラウザの画面表示でのレイアウトを使ってページごとにレイアウトされたDOMを作ります。それを印刷したとき、もしブラウザの画面表示と印刷とで文字組版・行組版結果が異なっていると、印刷したらレイアウトが崩れてしまうことになります。そのためこの修正では、常に段組みの指定（CSSにおいて、1段組の指定 `column-count: 1` も段組の処理となる）をすることで、画面表示でも印刷と同様に、古いレイアウトエンジンのほうが使われるようにしました。

ルビと親文字とがフォントによって離れてしまう問題は、新しいレイアウトエンジンのほうでは改善されているようですね。
Chromiumの開発者によると、来年には新しいレイアウトエンジンが印刷と段組みにも対応して、すべて新しいレイアウトエンジンに切り替わるらしいですので、そうしたらこの問題は改善するでしょう。

当面の対策としては、この問題が起きないフォントを使うことです。macOSに付属の日本語フォント Hiragino Mincho ProN などではルビと親文字とが離れすぎることはありません。Windowsでは "BIZ UDMincho" は大丈夫なようです。テストしました:

https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/774ed739994bd8371bcfcaa80752a06d/raw/ruby-line-height-test2.html

![Screen Shot 2021-10-29 at 0 37 21](https://user-images.githubusercontent.com/3324737/139289199-5ad739fe-b42f-4660-bb29-f0af60639c4c.png)

テストしたHTMLはGistに置いてます: https://gist.github.com/MurakamiShinyu/774ed739994bd8371bcfcaa80752a06d

**Comment by MurakamiShinyu** [comment]
Chrome 108から、画面表示と印刷とでルビのレイアウトが変わる問題は解消して、Vivliostyleでもプレビュー、印刷ともルビと親文字とが離れることはなくなったはずなので、このissueはクローズします。
