### ISSUE TITLE
Viewer zoom value should be kept on reloading

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#825]

**Comment by kenhys** [comment]
Using lower display resolution (e.g. 1024x768), it reduces productivity a bit (need to disable fit to screen everytime) . :disappointed:

**Comment by MurakamiShinyu** [comment]
- Resolved in #842 

Test:
- https://vivliostyle-git-feat-viewer-zoom-url-param-vivliostyle.vercel.app/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/shirouma/index.html&zoom=1
- https://vivliostyle-git-feat-viewer-zoom-url-param-vivliostyle.vercel.app/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/shirouma/index.html&zoom=2.5
- https://vivliostyle-git-feat-viewer-zoom-url-param-vivliostyle.vercel.app/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/shirouma/index.html
