### ISSUE TITLE
When writing vertically, the position of footnotes (float: footnote) is wrong.

### ISSUE THREAD

**Issue by butameron** [vivliostyle/vivliostyle.js#862]
**Describe the bug**
縦書き原稿の際、脚注（`float: footnote`）が誤った位置に表示されます。

**To Reproduce**
以下をvivliostyleで表示する。
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <style>
        @page {
            size: A5;
        }
        html {
            font-family: "源ノ明朝";
        }
        body {
            writing-mode: vertical-rl;
            line-height: 2;
        }
        .footnote {
            float: footnote;
        }
    </style>
</head>
<body>
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<span class="footnote">脚注テスト</span><br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
</body>
</html>
```
**Expected behavior**
脚注がページの末尾（左端）に表示される

**Screenshots**
ページの末尾ではなく、ページ末尾から二行目のところに表示されています。
![image](https://user-images.githubusercontent.com/19877154/152723984-c8d5dff7-879a-482f-973f-2590df09c8fa.png)

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Chrome
- Version: 97.0.4692.99（Official Build） （64 ビット）

**Additional context**

**Comment by MurakamiShinyu** [comment]
報告ありがとうございます。だいぶ前からのバグでした。

- Duplicate of https://github.com/vivliostyle/vivliostyle.js/issues/392

**Comment by butameron** [comment]
すみません、重複でしたね。
検索不足でした。

色々試してみたところ、以下のように脚注エリアにネガティブマージンを追加すると、とりあえず回避はできるようでした。

```
@-adapt-footnote-area {
    word-break: break-all;
    margin-left: -1em;
}
```

**Comment by MurakamiShinyu** [comment]
@butameron 重複してても報告ありがとうございます。

Vivliostyleの脚注の処理はいろいろ直さなければならないと思っているので、それを必要としてくれる人がいることは励みになります。

issue検索して、すでに報告があったバグだったときでも、自分もそのバグで困っているとコメントがあると、バグ修正の優先度があがったりするので、よろしく。

**Comment by butameron** [comment]
いろいろ試してみたところ、挙動としては、脚注エリアのleftが「ページ左マージン＋（@-adapt-footnote-area の左マージン＋@-adapt-footnote-area の右マージン）×2」の値になっているようです。

例えば、スタイルが以下の例の時、leftが124になります。

```
        @page {
            size: A5;
            margin: 100px;
        }
        html {
            font-family: "源ノ明朝";
        }
        body {
            writing-mode: vertical-rl;
            line-height: 2;
            font-size: 14px;
        }
        .footnote {
            float: footnote;
            font-size: 14px;
        }
                
        @-adapt-footnote-area {
            display: block;
            padding:0;
            margin-block-start: 6px;
            margin-block-end: 6px;
        }

        @-adapt-footnote-area ::before {
            display: none;
        }
```

なぜマージンが増加しているのか、少しソースコードを追いかけてみたところ、page-floats.tsのsetFloatAreaDimensions()で、area.leftにマージン分が加算されているようです。１回目の呼び出しの時はarea.leftが112、2回目の呼び出しの時は124になっています。

スタックトレースは以下の通りです。

```
setHorizontalPosition (vtree.ts:1192)
setBlockPosition (vtree.ts:1200)
setFloatAreaDimensions (page-floats.ts:1287)
setFloatAreaDimensions (page-floats.ts:1093)
setFloatAreaDimensions (page-floats.ts:1093)
setupFloatArea (layout.ts:1245)
createPageFloatArea (layout.ts:1301)
layoutSinglePageFloatFragment (layout.ts:1336)
layoutPageFloatInner (layout.ts:1425)
(anonymous) (layout.ts:1663)
thenAsync (task.ts:551)
layoutPageFloat (layout.ts:1630)
layoutFloatOrFootnote (layout.ts:3232)
layout (layout-processor.ts:116)
(anonymous) (layout.ts:3266)
略
```

試しに、page-floats.ts:1287行目を以下のように変更すると、正常に表示されるようになりました。

```
        area.setBlockPosition(
          blockEnd - blockSize * area.getBoxDir(),
          blockSize,
        );
```

あくまでもこれは試しに作ったものですので、実際にはもう少し考慮が必要かと思います。

`@-adapt-footnote-area`の`margin-block-start: 6px;`が効かない点については、一般的には、脚注の左マージンは、ページの左マージンと相殺されるほうが本来望まれる挙動だと思われるので、結果的には、問題ない挙動といえると思います。

ただ、ページの左マージン＜脚注の左マージンの時や、ネガティブマージンの時にも効かないのは恐らく問題ですので、もう少し考慮が必要そうです。


追記：
……と思ったら、上記の修正でも、マージンもネガティブマージンも一応効いているようですね。
むしろページマージンと脚注エリアのマージンの相殺がされていない感じでしょうか。

**Comment by MurakamiShinyu** [comment]
Fixed in #865 

Test: https://vivliostyle-git-fix-issue862-vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/7cc5f257235c86c7ec69e64f902664ea/raw/issue862.html

**Comment by MurakamiShinyu** [comment]
@butameron 
調査ありがとうございます。おかげさまで `setBlockPosition()` でmargin/border/padding（これがblockSizeとouterBlockSizeとの差になる）が考慮されていないバグだと気がつきました。
