### ISSUE TITLE
Generate single text node for a footnote-marker pseudo element.

### ISSUE THREAD

**Issue by butameron** [vivliostyle/vivliostyle.js#863]
バグか仕様かわかりませんので、いったん機能要望として提出します。

**Is your feature request related to a problem? Please describe.**

float: footnote を使用した場合、脚注の疑似要素を再現するための`<span data-adapt-pseudo="footnote-marker"`タグなどが生成されます。その際、以下のようにcontentに複数の値を結合した文字列を設定している場合、複数のテキストノードが生成されます。

```
::footnote-call {
   content: "*"counter(footnote);
}
```

しかし、文字ごとにテキストノードが別れている場合、以下のようにtext-combine-upright:がそれぞれのテキストノードに別れて働くため、縦中横になりません。

```
::footnote-call {
   content: "*"counter(footnote);
   text-combine-upright: all;
}
```

![image](https://user-images.githubusercontent.com/19877154/152820709-7c9fdd2c-4ffc-419a-b90b-05f6dc5f88a5.png)

![image](https://user-images.githubusercontent.com/19877154/152820784-2450c5da-311e-4f18-b942-66d087b547c4.png)

**Describe the solution you'd like**

以下のように単一ノード内にテキストが含まれるようにし、縦中横が機能するようにする。

![image](https://user-images.githubusercontent.com/19877154/152821639-4f107edc-f023-48c4-b9e1-27a95befa332.png)
![image](https://user-images.githubusercontent.com/19877154/152821678-7c94f00a-e348-49af-897b-fdb026d49846.png)

**Describe alternatives you've considered**

現状の仕様のままとして、`writing-mode: horizontal-tb;`でがんばることも可能ですが、現実の用途では、`[1]`というような書式や、`*1`というような書式で脚注の記号を指定したいというニーズがあり、そういうケースでは、「縦中横にしたい」「脚注記号は1em幅に収めたい」と考えられるため、`text-combine-upright: all;`で縦中横になるほうが良いと思います。

**Additional context**

**Comment by MurakamiShinyu** [comment]
ラベルは bug に変えました。今の実装は、縦中横でどういう結果になるかという考慮がされていなかったということなので。

**Comment by MurakamiShinyu** [comment]
Fixed in #875 

Test: https://vivliostyle-git-fix-issue863-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/3182afb43eb4b690d84659a29b80fa6f/raw/issue863.html
