### ISSUE TITLE
Logfiles

### ISSUE THREAD

**Issue by zopyx** [vivliostyle/vivliostyle.js#88]
Right now VS uses global log files (for Mac and Linux). It should be possible to configure the logfiles by command-line or at least default to the current directory instead of writing to /tmp.

**Comment by skoji** [comment]
We have created [a repository to track Issues of Vivliostyle Formatter](https://github.com/vivliostyle/vivliostyle-formatter-issues), and moved this Issue to vivliostyle/vivliostyle-formatter-issues#5 .
