### ISSUE TITLE
crop marks color should not be C0 M0 Y0 K100 when converted to CMYK

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#910]
`@page { marks: crop cross; }` によりトンボ付きでPDF出力して印刷用にCMYKに変換したとき、トンボの色が C0 M0 Y0 K100 になると、分版出力したときに K 以外の版にトンボが出力されないということになります。

Chrome (Chromium) のPDF出力で、この問題があります。

簡単な解決方法として、現在はトンボの色を RGBのblack (= `#000000`) で出力しているのを少しだけ変えることです。たとえば `#010101` で出力します。そうすると K100 ではなくなります。
（RGBの `#010101` をVivliostyle CLIの `--press-ready` オプションでCMYKのPDFに変換して調べたところ C72 M67 Y67 K88 となった）

関連するVivliostyle CLIのissue:
- https://github.com/vivliostyle/vivliostyle-cli/issues/276

**Comment by UskeS** [comment]
トンボの色が各色ベタ（C100，M100，Y100，K100）になっていないものを見たことがありません。
ベタにならない＝網点化されるということなので，各版で線がかすれます。
トンボ自体，実際の所なくてもかすれていても印刷は可能でしょうが，ベタでないトンボを見たことがないので，印刷会社さんによっては戸惑うかもしれません。

**Comment by MurakamiShinyu** [comment]
はい、この解決方法はブラウザからのPDF出力を使うVivliostyle.js側でできる簡易なもので、C, M, Yのトンボがまったく出ないよりはマシになるというものです。

トンボの色を各色ベタ（C100，M100，Y100，K100）にすることについては、Vivliostyle CLI側での後処理で対応することになります。
