### ISSUE TITLE
Support no-comma CSS color functions 

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#940]
It would be nice if Vivliostyle would support the ever more popular no-comma CSS color functions for specifying color values with and without alpha channel.

They look like this:  rgb(255 128 80 / 0.8)

https://www.w3.org/TR/css-color-4/#rgb-functions

**Comment by MurakamiShinyu** [comment]
@depth42 Thanks for the feature request. I recognize that the CSS parser and validation mechanism implemented in Vivliostyle (its significant part comes from the base project https://github.com/sorotokin/adaptive-layout) need to be updated to support the latest CSS standards.

**Comment by MurakamiShinyu** [comment]
@depth42 
Please check Vivliostyle.js v2.16.0 (CLI v5.3.0) now supporting no-comma CSS color functions.

**Comment by depth42** [comment]
Great, thanks!
