### ISSUE TITLE
Support for Selectors Level 4

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#957]
Add support for Selectors Level 4.

spec: https://www.w3.org/TR/selectors-4/

Especially, the following pseudo classes added in Selectors Level 4 will be very useful.

- [The Matches-Any Pseudo-class: `:is()`](https://www.w3.org/TR/selectors-4/#matches)
- [The Specificity-adjustment Pseudo-class: `:where()`](https://www.w3.org/TR/selectors-4/#zero-matches)
- [The Relational Pseudo-class: `:has()`](https://www.w3.org/TR/selectors-4/#matches)

Sub issue(s):
- #828

**Comment by MurakamiShinyu** [comment]
- Implemented in #1025.

## Tests

The following test files are copied from MDN site (thanks)

- `:is()`
  - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:is
  - Test file: https://murakamishinyu.github.io/bugtest/selectors4/test-is.html
  - Test with Vivliostyle Viewer:  
    https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-is.html
- `:where()`
  - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:where
  - Test file: https://murakamishinyu.github.io/bugtest/selectors4/test-where.html
  - Test with Vivliostyle Viewer:  
    https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-where.html
- `:not()`
  - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:not
  - Test file: https://murakamishinyu.github.io/bugtest/selectors4/test-not.html
  - Test with Vivliostyle Viewer:  
    https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-not.html
- `:has()`
  - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:has
  - Test file: https://murakamishinyu.github.io/bugtest/selectors4/test-has.html
  - Test with Vivliostyle Viewer:  
    https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-has.html
- `:has()` + `:is()`
  - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:has
  - Test file 1: https://murakamishinyu.github.io/bugtest/selectors4/test-has-is-1.html
    - Test with Vivliostyle Viewer:  
      https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-has-is-1.html
  - Test file 2: https://murakamishinyu.github.io/bugtest/selectors4/test-has-is-2.html
    - Test with Vivliostyle Viewer:  
      https://vivliostyle-git-feat-selectors4-vivliostyle.vercel.app/#src=https://murakamishinyu.github.io/bugtest/selectors4/test-has-is-2.html

**Comment by MurakamiShinyu** [comment]
Test result screenshots

(compare Chrome's output and Vivliostyle's output)

<img width="817" alt="Screen Shot 2022-10-18 at 14 26 11" src="https://user-images.githubusercontent.com/3324737/196343155-ff52c17d-3e7b-4620-ba5e-af633b8f1403.png">

<img width="823" alt="Screen Shot 2022-10-18 at 14 26 30" src="https://user-images.githubusercontent.com/3324737/196343191-64a55d32-418a-4ca2-a573-0f158ec68f8e.png">

**Comment by depth42** [comment]
Great feature! Thank you.
