### ISSUE TITLE
Content overflow caused by line breaks in table cells that are not present in preview and appear in print

### ISSUE THREAD

**Issue by mochimochiki** [vivliostyle/vivliostyle.js#958]
**Describe the bug**
The presence of line breaks may differ between preview and print in some tables. 
Content overflow occurs when line breaks are included only at print and it caused some lines to be lost.

**To Reproduce**
1. Save the following html as "test.html"
2. Execute the command `vs preview test.html -s A4`.
3. Press the print button.

```html
<!DOCTYPE html>
<html lang="jp">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>test</title>
  <style>
    :root {
      font-size: 0.8rem; /* or font-size: 12px;*/
      font-family: "Yu Gothic";
    }
    td, th {
      padding: 0.4rem; /* or padding: 6px; */
    }
  </style>
</head>

<body>
<h1>test</h1>
<table>
<thead>
<tr><th>#</th><th>AAAAAAAAAAAAA</th><th>AAAAAAAAAAA</th><th>AAAAAAAAAAAAA</th><th>AAAA</th><th>AAAAAAAAAAAA</th></tr>
</thead>
<tbody>
<tr><td>1</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>2</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>3</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>4</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>5</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>6</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>7</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>8</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>9</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>10</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>11</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>12</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>13</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>14</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>15</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>16</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>17</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>18</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>19</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>20</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>21</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>22</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>23</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>24</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>25</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>26</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>27</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>28</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>29</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
<tr><td>30</td><td>128</td><td>100</td><td>512</td><td>190 x 379 x 400</td><td>2020</td></tr>
</tbody>
</table>
</body>
</html>
```

* When previewing: Each line is rendered as one line.
* print preview / printed PDF : each line is rendered as two lines (overflow occurs and some lines disappear)

**Expected behavior**
The same output is produced for both preview and print.

**Screenshots**
- Preview
![preview](https://user-images.githubusercontent.com/10450428/179343573-15756ec8-6645-4187-a65f-b67babbaba84.png)

- Print Preview (line 21-28 are lost)
![print_preview](https://user-images.githubusercontent.com/10450428/179343797-503b852b-1278-4a33-9d0d-dc2dc800587c.png)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 64bit / Windows 10 Pro 64bit
- cli: 5.2.4
- core: 2.15.8
- chromium: 104.0.5112.20 (64bit)

**Additional context**
- The width and height of the table may change slightly between preview and print, even if the presence of line breaks does not change.
- The same issue occurred in the following environment.
  - OS: Windows 11 Pro 64bit / Windows 10 Pro 64bit
  - cli: 4.2.1
  - core: 2.10.0
  - chromium: 93.0.4577.0 (64bit)

Is there any way to work around this issue?

**Comment by MurakamiShinyu** [comment]
Thank you for reporting the bug!

Fixed in #960.

Test with Vivliostyle Viewer:
- Before this fix (v2.15.8): https://vivliostyle.github.io/viewer/v2.15.8/#src=https://gist.githack.com/MurakamiShinyu/64d8c9593323b8d0f14a660d4bb2daac/raw/issue958-test.html&userStyle=data:,/*%3Cviewer%3E*/%0A@page%20%7B%20size:%20a4;%20%7D%0A/*%3C/viewer%3E*/
- After this fix: https://vivliostyle-git-fix-issue958-vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/64d8c9593323b8d0f14a660d4bb2daac/raw/issue958-test.html&userStyle=data:,/*%3Cviewer%3E*/%0A@page%20%7B%20size:%20a4;%20%7D%0A/*%3C/viewer%3E*/

Result screenshot (After this fix):
<img width="1159" alt="Screen Shot 2022-07-17 at 22 08 23" src="https://user-images.githubusercontent.com/3324737/179399892-e80d0b60-1135-4cdc-9b45-e6abfb7ea69c.png">

**Comment by mochimochiki** [comment]
Thank you for the quick investigation and fix !

**Comment by MurakamiShinyu** [comment]
By the way, I fixed another bug related with this test sample. See
- https://github.com/vivliostyle/vivliostyle.js/issues/608#issuecomment-1186761942

> In this test sample, font-size: 0.8rem is specified on :root, so the computed font-size value in body must be 12.8px (= initial font-size 16px * 0.8), but that was 10.24px (= 16px * 0.8 * 0.8) in the result before this fix.
