### ISSUE TITLE
Vivliostyle does not load fonts specified in @font-face CSS rule

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#976]
**Description**
When paginating a document which makes use of symbols from the Font Awesome, the fonts are not loaded by Vivlostyle and instead of symbols only squares are appearing.

**To Reproduce**
Extract the attached archive "FontAwesomeTest.zip" and paginate the contained file "test.html" with Vivliostyle. 

**Expected behavior**
The paginated file should show a light bulb image and a sentence. (The file should load the "all.css" file from font awesome and the according woff font files.)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 12
 - Safari 15

**Additional context**
When opening the "test.html" file directly in Safari, the icon is rendered correctly.

[FontAwesomeTest.zip](https://github.com/vivliostyle/vivliostyle.js/files/9351292/FontAwesomeTest.zip)

**Comment by MurakamiShinyu** [comment]
In your "test.html" file in [FontAwesomeTest.zip](https://github.com/vivliostyle/vivliostyle.js/files/9351292/FontAwesomeTest.zip), `<link rel="stylesheet" href="../Paginator.css">` is used but the file "../Paginator.css" is not found. I couldnot reproduce the problem with this HTML file.

I could reproduce the bug with the following test:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="FontAwesome/all.css">
</head>
<body>
  <i class="fa fa-lightbulb"></i>
</body>
</html>
```

It seems that there is a bug in the CSS parser in Vivliostyle.js and the problem occurs during parsing "all.css".

With the following test, using only small part copied from the "all.css", no error occurs: 

```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <style>
    .fa {
      font-family: var(--fa-style-family, "Font Awesome 6 Free");
      font-weight: var(--fa-style, 900);
    }

    .fa {
      -moz-osx-font-smoothing: grayscale;
      -webkit-font-smoothing: antialiased;
      display: var(--fa-display, inline-block);
      font-style: normal;
      font-variant: normal;
      line-height: 1;
      text-rendering: auto;
    }

    .fa-lightbulb::before {
      content: "\f0eb";
    }

    @font-face {
      font-family: 'Font Awesome 6 Free';
      font-style: normal;
      font-weight: 900;
      font-display: block;
      src: url("FontAwesome/fa-solid-900.woff2") format("woff2");
    }
  </style>
</head>

<body>
  <i class="fa fa-lightbulb"></i>
</body>

</html>
```

**Comment by depth42** [comment]
Ah, I am so sorry, I compressed the wrong html file. But you already could reproduce the bug. Let me know if you need additional infos.
