### ISSUE TITLE
Using CSS variable breaks cascading

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#979]
**Describe the bug**
The order of CSS cascading seems to be affected by the use of a CSS variable.

**To Reproduce**
From the attached zip archive "VivliostyleVariablesBug.zip" paginate both contained files "wrong.html" and "correct.html" with Vivliostyle. 

**Expected behavior**
The background color behind the word "Test" should be green in both cases, but in the wrong case, it is white.
The only difference between the two files is that in the wrong case, the table background color - which should get overridden by cascading anyway - comes from a variable.

**Screenshots**
I attached screenshots from the paginations of both files in which you can spot the difference.

**Desktop (please complete the following information):**
 - mac OS 13
 - Safari 16

[VivliostyleVariablesBug.zip](https://github.com/vivliostyle/vivliostyle.js/files/9380287/VivliostyleVariablesBug.zip)
<img width="873" alt="wrong" src="https://user-images.githubusercontent.com/207403/185574073-acd09e17-a09a-450a-b837-93f7987f8341.png">
<img width="641" alt="correct" src="https://user-images.githubusercontent.com/207403/185574172-f063bb04-483c-44da-b32a-6292a1aa69c7.png">

**Comment by MurakamiShinyu** [comment]
@depth42 Thanks for the bug report! I will investigate and fix it.

**Comment by MurakamiShinyu** [comment]
It seems there is a problem on shorthand property processing when the shorthand property has a variable, such as `background: var(--background-table-color)`.
(There is no problem on non-shorthand property, e.g., `background-color: var(--background-table-color)`.)

**Comment by MurakamiShinyu** [comment]
Fixed in #984.
