### ISSUE TITLE
Remove not working custom properties from sample CSS files

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#99]
CSS files of published samples has some custom properties, but Vivliostyle does not support them now.
They should be removed since they are confusing to users.

**Comment by johanneswilm** [comment]
It seems that none of the samples are currently working, except the niimi ones, correct? Is there a list somewhere of the properties we currently do support?

**Comment by frivoal** [comment]
by custom properties, we're talking about those that start with --. This kind of custom properties https://drafts.csswg.org/css-variables-1/

**Comment by kwkbtr** [comment]
FIxed by #138.
